### ISSUE TITLE
README.md file should contain a section describing the debug inside the IntelliJ Idea using the gradle

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#100]
### I suggest to add the following section to the README.md file so new users can learn how to debug using IntelliJ Idea IDE quickly and elegantly:

Quarkus debugging using IntelliJ Idea IDE
------------------------------------------
The debugging of the Quarkus Tools using IntelliJ Idea IDE is possible by following these steps:

1) import the Quarkus Tools plugin source code into the IntelliJ Idea
2) open the Gradle window in the IntelliJ Idea (View->Tool Windows->Gradle)
3) in the Gradle window search for the **runIde** task->context menu->Debug (path to the the runIde gradle task - intellij-quarkus->Tasks->intellij->runIde)

**Comment by fbricon** [comment]
We should put these instructions in CONTRIBUTING.md instead.
Closing as superseded by #768
