### ISSUE TITLE
Preselected RESTEasy JAX-RS extension does not have the INCLUDED label

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#101]
I suggest to add the INCLUDED label to the preselected RESTEasy JAX-RS extension as it is on quarkus.io web:

<img width="217" alt="82153573-8692a680-9868-11ea-9b6e-2859c542f47d" src="https://user-images.githubusercontent.com/43820055/82160193-e8b4d100-9893-11ea-8432-c6bcdf4ec509.png">

**Comment by jeffmaury** [comment]
Duplicates of #65
