### ISSUE TITLE
Support for microprofile.command.configuration.update command

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/intellij-quarkus#1043]
Supporting `microprofile.command.configuration.update` will give the capability to exclude some error with pattern for appication.properties (helpfull for custom properties)

To support validation exclude we need to provide an UI settings with some tables to add/remove exclude pattern

**Comment by fbricon** [comment]
This depends on having a preferences page https://github.com/redhat-developer/intellij-quarkus/issues/794

**Comment by angelozerr** [comment]
We have already a preference page for MicroProfile / Java and MicroProfile / Properties which hosts codelens / inlayhint setting but we should move them, see https://github.com/redhat-developer/intellij-quarkus/issues/1044
