### ISSUE TITLE
Perception conflict between Red Hat and JetBrains Quarkus plugins

### ISSUE THREAD

**Issue by brunobat** [redhat-developer/intellij-quarkus#1045]
When using Intellij Idea ultimate, there are image clashes between Red Hat and JetBrains Quarkus plugins.
They have the same name and almost the same collor:

![image (5)](https://github.com/redhat-developer/intellij-quarkus/assets/2318030/68e1997b-6f50-43cf-9b5c-dfac74c4a495)
![image (4)](https://github.com/redhat-developer/intellij-quarkus/assets/2318030/6e6f8f02-448a-4246-9e8d-4217c83f3a31)
![image (3)](https://github.com/redhat-developer/intellij-quarkus/assets/2318030/8864beff-f0ab-4f9f-a1ea-7fb1a8489972)

But it gets worse!
If you use the light theme, there is no way to know who is who.

It would be nice to get a precise distiction between the two plugins.

**Comment by angelozerr** [comment]
Thanks @brunobat @arik-dig to have reported this issue.

@mohitsuman have you some idea how to fix this issue?

**Comment by brunobat** [comment]
> The plugins are named "Quarkus" (bundled) and "Quarkus Tools" (by rht), but in the UI, they are both shown as "Quarkus".
> 
> Perhaps the easiest fix is to ensure the Red Hat plugin reads "Quarkus Tools" in the view, as it does in the plugin name?

That works for me.

**Comment by angelozerr** [comment]
> Perhaps the easiest fix is to ensure the Red Hat plugin reads "Quarkus Tools" in the view, as it does in the plugin name?

Good suggestion!

@fbricon @mohitsuman @jeffmaury it makes senses for you?

**Comment by jeffmaury** [comment]
+1

**Comment by brunobat** [comment]
<img width="653" alt="Screenshot 2023-08-31 at 11 33 51" src="https://github.com/redhat-developer/intellij-quarkus/assets/2318030/554bd8b1-0b29-4dde-813a-6a708bc6ffce">

Can someone please give some alternative name to the Plugin?
This is super confusing.

**Comment by ia3andy** [comment]
@jamescobb could you make a logo for the Quarkus Tools, to show that it's Quarkus but part of the Quarkus Tools?

**Comment by angelozerr** [comment]
It should be fantastic if we could have a logo for IJ Quarkus.

But I wonder if it should be better to provide a  new quarkus logo for quarkus tooling that we  could use in vscode quarkus, jboss tools ec liose ide.

A quick and basic idea is to have the same quarkus logo with a key tools

**Comment by fbricon** [comment]
Trying "Quarkus Dev Mode":

<img width="1152" alt="Screenshot 2023-09-05 at 14 26 46" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/54ad24f6-b58e-43d7-b944-6070b8638458">

WDYT?
