### ISSUE TITLE
Show LSP completion item documentation in popup

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/intellij-quarkus#1046]
I discovered that IJ provide this popup support 

![image](https://github.com/redhat-developer/intellij-quarkus/assets/1932211/25c920c5-ef97-46d4-9ca3-27ce49348d81)

We should fill it with  LSP completion item documentation

**Comment by fbricon** [comment]
![image](https://github.com/redhat-developer/intellij-quarkus/assets/1932211/480d871b-d42e-4d46-bed9-51075f3ab27b)
