### ISSUE TITLE
Preselect first extensions category in the wizard

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#105]
![New Project](https://user-images.githubusercontent.com/43820055/82187488-ca2ef400-98ec-11ea-91b8-0db2fe014685.png)

**Comment by zcervink** [comment]
@jeffmaury update on this issue - as I have already commented on the PR, I suggest to close the PR and the issue because it already has been fixed by another merged PR.

**Comment by jeffmaury** [comment]
I tested it against master and got the issue so I think it's useful

**Comment by zcervink** [comment]
@jeffmaury I am sorry, I must accidentally test it against another branch than master. After testing it against master I have found that the issue is still there. I am going to test the PR branch now.
