### ISSUE TITLE
Storing VirtualFile instead of Document for opened document

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/intellij-quarkus#1082]
The LanguageServerWrapper works with Document instead of VirtualFile. I think this choice has been done because LSP4E works like this. LSP4E did this choice because they wanted to manage IFile, File and editor without file.

In IJ, VirtualFile is a File, but it exists an implementation LightVirtualFile which is independant of the file system (the content is in memory instead of get it from the file system), so I wonder if we could remove the `Map<URI, DocumentContentSynchronizer>` and uses just only `List<VirtualFile>` for the opened file.

I think it will simplify the code.

@jeffmaury what do you think about this idea?

**Comment by jeffmaury** [comment]
Just wondering because they don't have the same scope if I remember correctly

**Comment by angelozerr** [comment]
> Just wondering because they don't have the same scope if I remember correctly

What do you mean with scope?

**Comment by angelozerr** [comment]
The motivation about change Document to VirtualFile is when I'm trying to understand https://github.com/redhat-developer/intellij-quarkus/pull/1081 I read

https://plugins.jetbrains.com/docs/intellij/documents.html#how-long-does-a-document-persist

They say:

`Storing Document references in long-term data structures of a plugin will cause memory leaks.`

And today we store the Document.

**Comment by jeffmaury** [comment]
Agree but when document is closed it should be evicted.

I mean Document has Project scope and VirtualFile has app/JVM scope.

So if the same file is opened in 2 different projects, you need to make sure LSP is properly setup with regards to editors

**Comment by angelozerr** [comment]
> So if the same file is opened in 2 different projects, you need to make sure LSP is properly setup with regards to editors

How to have this usecase? I'm trying to have this usecase for trying  to have this issue https://github.com/redhat-developer/intellij-quarkus/pull/1081

Anyway, Language server accessor which creates the language servers is mapped with a project scope,so I think we will have no problem.

**Comment by jeffmaury** [comment]
1. Create 2 empty IJ project into 2 different folders
2. Add a Maven module from an exiting Maven project into those 2 projects
3. Open the same file from the 2 IJ projects

**Comment by angelozerr** [comment]
Thanks!

It seems that Document instance are the same for the 2projects.

**Comment by jeffmaury** [comment]
So maybe they have the same scope, getting too old

**Comment by angelozerr** [comment]
I don't know.

In conclusion,are you OK to swith to VirtualFile?

**Comment by jeffmaury** [comment]
I can't answer that would require me to look deeper into the code and do some testing.

But if they have the same scope that would be ok

**Comment by angelozerr** [comment]
Ok thanks for your feedback @jeffmaury !

I will try it.

**Comment by angelozerr** [comment]
While working on https://github.com/redhat-developer/intellij-quarkus/pull/1185 I notice that we spend our time to convert Document to VirtualFile (ex : to get the Uri of the document, we get the VirtualFile). In other words all code API are using Document but internally we convert it to VirtualFile to  get some information like Uri.
