### ISSUE TITLE
Support Reactive Routes

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#1114]
It would be nice if we had the same behavior as JAX-RS methods when using https://quarkus.io/guides/reactive-routes

**Comment by angelozerr** [comment]
I had created the issue for JDT https://github.com/redhat-developer/quarkus-ls/issues/914

**Comment by angelozerr** [comment]
I m working on this issue. @gastaldi hope you will able to to review it because I have no skills with reactive route
