### ISSUE TITLE
NPE when using records as configuration holder

### ISSUE THREAD

**Issue by E14** [redhat-developer/intellij-quarkus#1118]
The IDE encounters an NPE when records are used as a configuration holder like this:

```java
package org.acme;

import org.eclipse.microprofile.config.inject.ConfigProperty;

import io.quarkus.arc.VetoedProducer;
import jakarta.enterprise.context.Dependent;

@Dependent
public record RecordConfiguration(@VetoedProducer @ConfigProperty(name = "acme.username") String username) {}
```

Exception trace (trimmed, [full stack trace attached](https://github.com/redhat-developer/intellij-quarkus/files/12408766/StackTrace.log)):
```
  Cannot compute MicroProfile properties for the Java element 'PsiRecordComponent:username'.
  
  java.lang.NullPointerException: Cannot invoke "com.intellij.psi.PsiMethod.getName()" because "method" is null
at com.redhat.devtools.intellij.lsp4mp4ij.psi.core.utils.PsiTypeUtils.getSourceMethod(PsiTypeUtils.java:143)
at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.config.properties.MicroProfileConfigPropertyProvider.collectProperty(MicroProfileConfigPropertyProvider.java:131)
at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.config.properties.MicroProfileConfigPropertyProvider.collectProperty(MicroProfileConfigPropertyProvider.java:85)
at com.redhat.devtools.intellij.lsp4mp4ij.psi.internal.config.properties.MicroProfileConfigPropertyProvider.processAnnotation(MicroProfileConfigPropertyProvider.java:72)
```

I have created a [reproducer.zip](https://github.com/redhat-developer/intellij-quarkus/files/12408773/reproducer.zip), you can manually try removing `PojoConfiguration` or `RecordConfiguration` classes from the project.

Projects build absolutely fine using this.

### Environment
- OS: Windows 10
- IntelliJ: 2023.2 (Community Edition) #IC-232.8660.185, built on July 26, 2023
- IntelliJ-Quarkus: 1.25.0.522

### Reproducing

- Import the reproducer
- The exceptions usually are thrown upon loading the project, and regularly when opening any `*.properties` file or a config holder, though there seems to be some rate-limiting or caching involved as it's not thrown every single time and also not immediately after .

**Comment by fbricon** [comment]
Thanks for the reproducer, it's very helpful. Now I need to figure out how to handle records ;-)
<img width="1904" alt="Screenshot 2023-08-22 at 15 20 33" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/a709b39d-895f-4f43-b296-0ae05f80cc68">

**Comment by fbricon** [comment]
@E14 you can follow these [instructions](https://github.com/redhat-developer/intellij-quarkus#testing-the-ci-builds) to try the CI build from https://github.com/redhat-developer/intellij-quarkus/actions/runs/5939620743.

**Comment by E14** [comment]
@fbricon wow, that was quick! I hope I didn't stress you, that was definitely not my intention

Anyway, I tested it in my larger projects (and the reproducer) and it's looking good, no errors so far, and usually I would get them as soon as I open the project and again when opening any properties file or changing the config holder. (*just realised that was missing info here, sorry)
