### ISSUE TITLE
Improve performance of Quarkus deployment jar support

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/intellij-quarkus#1143]
When completion, validation, etc  is done in application.properties, the properties search must be done in the quarkus deployment JAR too. To do that, the JAR from Java classpath are scanned and we search in each JAR if a quarkus depliement is declared in the properties file of the JAR, if a quarkus deployment is declared, we download it and add it to the class path.

There are 2 problems with this process:

 * it can take some time
 * the quarkus deployment computation is done several times when a library is added (this problem occurs sometimes)

**Comment by E14** [comment]
> @E14 I have a draft PR https://github.com/redhat-developer/intellij-quarkus/pull/1221 which should improve the Quarkus deployment support :
> 
> * Quarkus deployment should be done only if need (when application.properties dooes validation, when there is a completion on applictaion.properties, etc) and not on each classpath changes
> * the compute of Quarkus deployment should be very fast because I resolve the only the Quarkus deployment artifact and dont resolve transitly the deployment artifact.
> 
> To reproduce your isse, you add a depndency in pom.xml and you refresh your pom.xml and you do that several times. You should see your issue. With my draft PR https://github.com/redhat-developer/intellij-quarkus/pull/1221, I cancel the Quarkus deployment process as soon as there is a classpath changes.

@angelozerr Thank you! I'm now able to reproduce this consistently by simply changing any dependency in the pom and then causing additional builds (like adding a line in any file, then saving)

I see you're still at work here, but if you have a build that you want me to test (if it helps you out), just give me a nudge.
