### ISSUE TITLE
Qute support for multi module project doesn't work

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/intellij-quarkus#1164]
@ia3andy please be aware that multi module project with Qute doesn't work (you need to open the Qute project and not a project which could have one / several Qute module)

To fix this issue, it requires some work on Qute LS https://github.com/redhat-developer/quarkus-ls/issues/930

**Comment by gbourant** [comment]
I was about to open a new issue but i will post it here since it seems relevant.


Assume you have the following template

```html
{#include root.html }
{/include}
```

The root.html is defined in another project. When i press Ctrl and hover with the mouse the `root.html` , it says that it is unable to find it and asks if i want to create it.

**Comment by fbricon** [comment]
@gbourant Can you attach sample projects?

**Comment by gbourant** [comment]
Sure @fbricon, soon it will be available.

**Comment by gbourant** [comment]
Alright, the project is available [here](https://github.com/gbourant/multi-module-template-test):

Just run `./mvnw clean quarkus:dev` in the root directory and it will build `project-a` and then run `project-b`.

So the `project-a` has the `root.html` and the `project-b` uses it at the `index.html`

`root.html` at `project-a`
```html
hi from root template in project-a

<p>{#insert /}</p>
``` 

`index.html` at `project-b`
```html
{#include root}
    message from project-b
{/include}
```

So you should something like this:

![image](https://github.com/redhat-developer/intellij-quarkus/assets/9791051/a92f900d-a46d-47a6-a9e6-58e0cb48a09e)

Now you should be able to reproduce it. ( if it doesn't work remember to load maven changes )

**Comment by angelozerr** [comment]
Thanks @gbourant for sharing a sample with Qute multi module. Your usecase is not trivial but it highlights that we need to load dependencies between project too in https://github.com/redhat-developer/quarkus-ls/issues/930

**Comment by angelozerr** [comment]
I have supported multiple project on Qute language Server and JDT side in https://github.com/redhat-developer/quarkus-ls/pull/940

See demo with vscode at https://github.com/redhat-developer/quarkus-ls/pull/940#issuecomment-1728937725

Once this PR will be merged,I will create a PR for IJ to consume the Qute Language server which supports multi module and implement the new services on IJ side which need to collect a lits of Qute projects coming from multimodules
