### ISSUE TITLE
Qute fragments doesn't work with non inner Templates Java file

### ISSUE THREAD

**Issue by gbourant** [redhat-developer/intellij-quarkus#1169]
When i define a fragment in a `@CheckedTemplate` class the Code Lens shows `Create path/to/file.html` while the file exist. (attached image)

**Suggestion**

Depending on the situation it should do the following:

1. If the file does not exist, create the file, create the fragment in that file and jump to that file/fragment.
2. If the file does exist, but the fragment does not exist, create the fragment in that file and jump to that fragment.
3. If the file does exist and the fragment does exist just jump to that fragment.

![image](https://github.com/redhat-developer/intellij-quarkus/assets/9791051/fc8ec624-d962-4f92-b4b2-3c7457e6dac5)

**Comment by angelozerr** [comment]
At first I'm surprised that fragment report error and codelens show create instead of Open when fragment is used. The existing code looks like to the code that we write in Quarkus LS (JDT https://github.com/redhat-developer/quarkus-ls

I need to debug why it doesn't work.

Jumping from Java to template with proper location on fragment requires some inprovement on Qute Language Server, see https://github.com/redhat-developer/quarkus-ls/issues/776

**Comment by angelozerr** [comment]
@gbourant I have the impression that you are using a very old version of IJ Quarkus.

Fragment is working for me (no validation error, jump to the file template)

![FragmentOnIJ](https://github.com/redhat-developer/intellij-quarkus/assets/1932211/5c02562a-bc8c-44f2-bf12-49b852dfdd8a)

Which version are you using? Yesterday we have released 1.28.

If you are using not an old version of IJ Quarkus, could you share your project please.

**Comment by angelozerr** [comment]
@gbourant I can reproduce your issue with

```java
package org.acme;

import io.quarkus.qute.CheckedTemplate;
import io.quarkus.qute.TemplateInstance;

@CheckedTemplate
public class Templates {

    public static native TemplateInstance auth$emailVerification(String email);
}
```

The issue is when you are using not an inner class. I'm investigating the issue.

**Comment by gbourant** [comment]
Thank you @angelozerr for your work, i was kind of busy and didn't have time to answer. But you found out alone, good job!
