### ISSUE TITLE
Show error when redifining Qute templates location

### ISSUE THREAD

**Issue by pablobastidasv** [redhat-developer/intellij-quarkus#1186]
I'm trying Qute the plugin is working well for me but, I found that when I redefined the location of the templates by using `@CheckedTemplate(basePath = "emails", defaultName = CheckedTemplate.UNDERSCORED_ELEMENT_NAME)` then a error is shown because it cannot find the template in the default package.

![image](https://github.com/redhat-developer/intellij-quarkus/assets/8153449/b9d3289f-ede8-4c4d-8c65-b031a70bbab9)

**Comment by fbricon** [comment]
Mmm defaultName = CheckedTemplate.UNDERSCORED_ELEMENT_NAME is not yet supported, but I'm not sure this is the issue. What's the path to your home template?

**Comment by fbricon** [comment]
https://github.com/redhat-developer/intellij-quarkus/pull/1173 hasn't been released yet, but please [try the latest CI build ](https://github.com/redhat-developer/intellij-quarkus/#testing-the-ci-builds)

**Comment by pablobastidasv** [comment]
Great, it worked like a charm. Looking forward for the release.
