### ISSUE TITLE
Application.properties completion and validation sometimes fails while working with the file

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#119]
While working with the application.properties file the completion and validation sometimes fails to offer some properties and after typing them manually the properties ends being underlined with yellow color. I have managed to reproduce this issue only 2 times, it appears only sometimes.

**Steps to reproduce:**
1) Open the application.properties, try to add some property such as "quarkus.application.name=xyz"
2) Add some more properties, create some mess, define the quarkus.application.name property several times
3) Copy/paste some lines of code, simulate working with the file
4) Delete the whole content of the application.properties file
5) Define a property such as "quarkus.application.name=xyz"

**Note:** I think this issue has something in common with the situation when user define some properties more than one. When you define a property 2 or 3 times the validation underlines them but after some time working with the file something go wrong and the validation/completion fails for the properties that has been defined several times before.

**Fix:** Close and reopen the application.properties file

<img width="765" alt="Snímek obrazovky 2020-06-08 v 5 55 17" src="https://user-images.githubusercontent.com/43820055/83991308-a3446a80-a94c-11ea-8fa2-c7a39021be08.png">

<img width="336" alt="Snímek obrazovky 2020-06-08 v 5 51 00" src="https://user-images.githubusercontent.com/43820055/83991191-4e085900-a94c-11ea-88c9-e31d274cabf5.png">

**Comment by angelozerr** [comment]
It seems it is again a problem with editor synchronization with LSP language server fixed in https://github.com/redhat-developer/intellij-quarkus/pull/778

I tried the usecase and it is working for me. 

Please reopen the issue if you encounter again the problem.
