### ISSUE TITLE
quarkus.hibernate-orm.database.generation invalid validate value

### ISSUE THREAD

**Issue by zZHorizonZz** [redhat-developer/intellij-quarkus#1199]
I'm currently trying to use the following configuration:

```
quarkus.hibernate-orm.database.generation=validate
```

However, the extension doesn't recognize this as a valid value. According to the documentation for this property, the accepted values are:

```
Accepted values: none, create, drop-and-create, drop, update, validate
```

Upon inspecting the [quarkus-hibernate-orm-metadata.json](https://github.com/redhat-developer/intellij-quarkus/blob/abf9c7dae3d5689afc4b68a7d6c2c6507d5d1a52/src/main/resources/static-properties/quarkus-hibernate-orm-metadata.json), it appears that "validate" is the only value missing.

**Comment by angelozerr** [comment]
Right, is there any chance to have a PR to fix that?

**Comment by zZHorizonZz** [comment]
Here: #1200

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/intellij-quarkus/pull/1200
