### ISSUE TITLE
@Scheduled methods should be marked as implicitly used

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#1201]
e.g.
```java
    @Scheduled(every = "2s")
    public void every2s() {
        System.err.println("Wake up!");
    }
```
<img width="290" alt="Screenshot 2023-10-16 at 18 34 45" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/18bae4ba-6720-42cb-952a-6a6517e5259c">

The class must be in the  `@ApplicationScoped` as per  https://quarkus.io/guides/scheduler#standard-scheduling

**Comment by angelozerr** [comment]
Could you add a sample in the issue (without screenshot) please and show the result with or without ApplicationScoped
