### ISSUE TITLE
Qute template validation breaks when using Gradle

### ISSUE THREAD

**Issue by billoneil** [redhat-developer/intellij-quarkus#1224]
There are no issues with the templates and everything works correctly but I am getting errors with the Qute validation.

<img width="755" alt="image" src="https://github.com/redhat-developer/intellij-quarkus/assets/5205330/ae5ac7f3-5a39-4166-bfd0-d9b5fe39b985">

<img width="441" alt="image" src="https://github.com/redhat-developer/intellij-quarkus/assets/5205330/83f84348-8764-45cf-8e73-067b598c7871">

The templates are located here in the build directly and they do work as expected.

<img width="418" alt="image" src="https://github.com/redhat-developer/intellij-quarkus/assets/5205330/47a32c82-84ab-47e1-becf-904b419c9f8e">

**Comment by angelozerr** [comment]
Could you share your project please.

**Comment by billoneil** [comment]
I created a minimal repo here but I'm seeing different behavior there now. https://github.com/billoneil/quarkus-kotlin-qute

I am not getting any highlighting or completion 
<img width="364" alt="image" src="https://github.com/redhat-developer/intellij-quarkus/assets/5205330/b0b9f9c3-28ab-4b0a-96b5-7131e3b011f6">

**Comment by angelozerr** [comment]
Thanks @billoneil for sharing your project. I have imported your project and at first you need to wait that your project is indexing to benefit with Qute support. After IJ indexing is finishd, do you have syntax coloration ad completion support for Qute?

I have imported your project and there is indeed a problem. It seems that root path for template is in `src/test/resources/templates` instead of `src/main/resources/templates`. I need to investigate why.

**Comment by angelozerr** [comment]
The current problem is that `main`,`test`, and `native-test` are modules:

![image](https://github.com/redhat-developer/intellij-quarkus/assets/1932211/fd7be2df-f53e-4cb2-bb94-7c2a8255551b)

So we consider that there are 4 Qute projects. You can see that in LSP console:

![image](https://github.com/redhat-developer/intellij-quarkus/assets/1932211/fe1c99d9-6922-47be-a2ec-19d64d1cebef)

 by activating verbose message:

![image](https://github.com/redhat-developer/intellij-quarkus/assets/1932211/110a5e42-3785-4d30-a951-d5a0e3bd5a18)

```
[Trace - 12:19:16] Sending response 'qute/template/projects - (4)'. Processing request took 4ms
Result: [
  {
    "uri": "rest-kotlin-quickstart.test",
    "templateBaseDir": "file:/C:/Users/azerr/git/quarkus-kotlin-qute/src/test/src/main/resources/templates/",
    "projectDependencyUris": [
      "rest-kotlin-quickstart.main"
    ]
  },
  {
    "uri": "rest-kotlin-quickstart.native-test",
    "templateBaseDir": "file:/C:/Users/azerr/git/quarkus-kotlin-qute/src/native-test/src/main/resources/templates/",
    "projectDependencyUris": [
      "rest-kotlin-quickstart.test",
      "rest-kotlin-quickstart.integrationTest",
      "rest-kotlin-quickstart.main"
    ]
  },
  {
    "uri": "rest-kotlin-quickstart.main",
    "templateBaseDir": "file:/C:/Users/azerr/git/quarkus-kotlin-qute/src/main/src/main/resources/templates/",
    "projectDependencyUris": []
  },
  {
    "uri": "rest-kotlin-quickstart.integrationTest",
    "templateBaseDir": "file:/C:/Users/azerr/git/quarkus-kotlin-qute/.idea/src/main/resources/templates/",
    "projectDependencyUris": [
      "rest-kotlin-quickstart.test",
      "rest-kotlin-quickstart.main"
    ]
  }
]

```

With maven project, themodule is the root project, not main,test. I wonder if it is a standard layout for gradle to have a module for main, test?

**Comment by billoneil** [comment]
@angelozerr all of the referenced templates live in the same module is this a problem because it doesn't know which project to look in?

**Comment by fbricon** [comment]
for now our language servers don't support kotlin projects, so not finding templates might be a side effect (or not). We need to investigate.

**Comment by angelozerr** [comment]
> @angelozerr all of the referenced templates live in the same module is this a problem because it doesn't know which project to look in?

I need to investigate more, but the first problem is that we consider that there are 4 Qute projects (because of module) although there is just one module.

> for now our language servers don't support kotlin projects, so not finding templates might be a side effect (or not). We need to investigate.

@fbricon for this issue, the problem is about modules. In Gradle, it seems that main,test are modules although in maven  those folders are not a module.

**Comment by fbricon** [comment]
OK the same problems occurs on gradle projects without kotlin.

**Comment by angelozerr** [comment]
@billoneil we have fixed problem with gradle project, but your project will not work again because you are using Kotlin which is not a trivial issue. Please follow the issue https://github.com/redhat-developer/intellij-quarkus/issues/482
