### ISSUE TITLE
'quarkus.resteasy-reactive.path' is unrecognized in application.properties

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#1249]
This should be valid as per https://quarkus.io/guides/resteasy-reactive#declaring-endpoints-uri-mapping:
> quarkus.resteasy-reactive.path=/api

but it's unrecognized:
<img width="667" alt="Screenshot 2023-10-31 at 13 21 34" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/70667273-0259-48bb-9e3b-82527061bbf4">

It's a build time property, so that shouldn't be a deployment jar issue. Maybe a converter problem?

**Comment by angelozerr** [comment]
Or it is an hard coded property and if it is the case we need to declare it with custom properties

**Comment by fbricon** [comment]
I found it here: https://github.com/quarkusio/quarkus/blob/e6423a404758f30e121506a311ec9a445cc27dc9/extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/main/java/io/quarkus/resteasy/reactive/server/deployment/ResteasyReactiveServerConfig.java#L20

**Comment by fbricon** [comment]
Could mulitple [`@ConfigMapping(prefix = "quarkus.resteasy-reactive")`](https://github.com/search?q=repo%3Aquarkusio%2Fquarkus+%40ConfigMapping%28prefix+%3D+%22quarkus.resteasy-reactive%22%29&type=code) be a problem?

**Comment by fbricon** [comment]
This is a duplicate of #1189, as today, I see that `quarkus.resteasy-reactive.path` and the quinoa properties are available without errors.  

Closing.
