### ISSUE TITLE
External links are not loaded in external browser anymore after installing the plugin

### ISSUE THREAD

**Issue by alerosmile** [redhat-developer/intellij-quarkus#1254]
Clicking a external link in javadoc usually opens the external browser. After installing this plugin, the links are opened in an editor tab:

![image](https://github.com/redhat-developer/intellij-quarkus/assets/26764588/6b63e541-7c4f-4dab-ac8c-771fd73c733f)

![image](https://github.com/redhat-developer/intellij-quarkus/assets/26764588/efda9cab-5272-443b-a1b7-b00ffda55689)

This is probably caused by [LSPDocumentationProvider#handleExternalLink](https://github.com/redhat-developer/intellij-quarkus/blob/f599f3ce417d13134007b5a2b93357681c29d659/src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/documentation/LSPDocumentationProvider.java#L148). Returning `false` restores the expected behaviour.

**Comment by fbricon** [comment]
which version of IJ are you using?  I'm unable to see that view external documentation button

**Comment by alerosmile** [comment]
I'm using 2023.2.4.

First you have to setup the documentation URL:
![image](https://github.com/redhat-developer/intellij-quarkus/assets/26764588/b1369b14-2666-4db5-8c26-016710a50620)


Then you can either right-click on a javadoc popup and select `View External Documentation`
![image](https://github.com/redhat-developer/intellij-quarkus/assets/26764588/ec455039-c0f3-4197-953c-85cacd341fa2)

or enable the toolbar by clicking the kebab item:
![image](https://github.com/redhat-developer/intellij-quarkus/assets/26764588/a67a757b-ede4-435e-8bc2-0ee1b68ca88d)

IntelliJ sets up an internal web server for some of the docs. This doesn't work either:
![image](https://github.com/redhat-developer/intellij-quarkus/assets/26764588/06324d8b-db54-4541-b08b-0ddb1b518d4d)

**Comment by fbricon** [comment]
@alerosmile  thanks for the instructions! I managed to find a simpler way to reproduce the issue. Please try this [CI build](https://github.com/redhat-developer/intellij-quarkus/suites/17941506821/artifacts/1031154147), by following [these instructions](https://github.com/redhat-developer/intellij-quarkus#testing-the-ci-builds) and let us know if that fixes your issues.

**Comment by alerosmile** [comment]
It works, thank you!

**Comment by angelozerr** [comment]
> It works, thank you!

Thanks @alerosmile for your feedback. The PR has been merged.
