### ISSUE TITLE
Support CDI scope annotations in interfaces

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#1290]
Some extensions, like the [Quarkus-langchain4j](https://github.com/quarkiverse/quarkus-langchain4j) and the REST Client, support specifying scope annotations in interfaces. That serves as a hint for the Quarkus processor to generate a bean with the provided annotation.  

It would be nice if IntelliJ didn't mark that as an error:

![image](https://github.com/redhat-developer/intellij-quarkus/assets/54133/0605863e-dd5a-4d78-aabd-a11727fd7e73)

**Comment by angelozerr** [comment]
@gastaldi have you some idea how to ignore this error (check if `@RegisterAiService` annotation is used?)

**Comment by gastaldi** [comment]
@angelozerr that's a good question. I think it depends on the features each extension provides. Perhaps @geoand or @ladicek may have an idea?

**Comment by angelozerr** [comment]
> Currently this is also used in REST Client

But is there some annotations that we need to check?

**Comment by gastaldi** [comment]
Maybe start with `@RegisterRestClient` and the `@RegisterAiService`?

**Comment by gastaldi** [comment]
I wonder if the extension could provide some sort of hint to the IDE plugin to avoid hard-coding that in the plugin

**Comment by angelozerr** [comment]
> I wonder if the extension could provide some sort of hint to the IDE plugin to avoid hard-coding that in the plugin

You mean a settings to exclude some validation rules according some rules like "validate this rule only if there are this annotation" ?

**Comment by gastaldi** [comment]
> You mean a settings to exclude some validation rules according some rules like "validate this rule only if there are this annotation" ?

Yeah, something like that, or a marker file in the extension somehow

**Comment by angelozerr** [comment]
Managing validation with declarative mean can be very nice but can be limitated. For instance if you need to add a new rule like "only if this class exists in the classpath", it can be awful to customize it and awfull to develop a nice UI.

Before implementing a validation rule, we need to understand how it works to implement the best validatuon rule.

@gastaldi @geoand have you some idea where we could find more docs about this new validation rule, or better do you know who has implemented this new validation rule?

**Comment by angelozerr** [comment]
I though that this error was reported by our olugin but it seems thie error is reported by IJ himself.

I don't know if IJ provides an extendion point to ignore the error.

**Comment by fbricon** [comment]
Quarkus tools doesn't produce this error:
<img width="421" alt="Screenshot 2023-12-15 at 10 51 05" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/2e7ced91-a79d-46d2-9cb1-f4d6880353d4">


This is caused by Jetbrains' Quarkus support. Please open a ticket in https://youtrack.jetbrains.com/issues?q=quarkus%20State:%20Open
