### ISSUE TITLE
Debug run config invalid with Gradle

### ISSUE THREAD

**Issue by Nikita-V0lkov** [redhat-developer/intellij-quarkus#1311]
When using quarkus-tools version 1.30.1 with gradle, **debug** button do nothing (maven works as intended).
Im using IJ Ultimate 2023.2.5 (bundled quarkus plugin disabled).
Quarkus-Tools version 1.28.0 works as intended in gradle and maven projects.

**Comment by angelozerr** [comment]
Thanks for reporting the issue.

We improve the run configuration to run it with Services view but it seems debug for gradle doesn't work. I need to investiage more the problem but I'm very usy for now with the LSP support which is broken for EEAP 2024.1

**Comment by ArtemenkoAndrii** [comment]
Have almost the same issue for Quarkus Tools 2.0.2 and IntelliJ IDEA 2024.2.0.2 (Community Edition).
After clicking "Debug" icon the IDE status line shows "Connecting Java debugger to port 60919" and nothing else happens

**Comment by angelozerr** [comment]
Indeed I need to find time to investigate this issue.

**Comment by angelozerr** [comment]
I created a fresh Quarkus project with Gradle and it works for me. 

@ArtemenkoAndrii @Nikita-V0lkov is it possibleto share your project please.

**Comment by ArtemenkoAndrii** [comment]
@angelozerr Sorry, my project is commercial. If you share your project, I'll try to run it on my side.

**Comment by angelozerr** [comment]
Try to create a project with our Quarkus wizard. Is it working?

**Comment by angelozerr** [comment]
Oh wait please. I have tried Run but not Debug, my bad-( Let's me try it.

**Comment by angelozerr** [comment]
Indeed I have the same problem than you, sorry for the noise.

**Comment by ArtemenkoAndrii** [comment]
no problems

**Comment by angelozerr** [comment]
@Nikita-V0lkov @ArtemenkoAndrii could you please install the build zip that you can download at https://github.com/redhat-developer/intellij-quarkus/actions/runs/10886132915 (see explanation at https://github.com/redhat-developer/intellij-quarkus?tab=readme-ov-file#testing-the-ci-builds) and tell me if you can now debug your Quarkus Gradle project?

Please try too tho run the config, and start the debug, stop it, restart etc to see if it works correctly. Thanks!

**Comment by ArtemenkoAndrii** [comment]
At first glance, it works. However, it seems like the debugger is being triggered twice.
![image](https://github.com/user-attachments/assets/f462154a-6d54-4772-a5c0-94c238fecd8c)

**Comment by angelozerr** [comment]
> However, it seems like the debugger is being triggered twice.

There are 2 stop because:

 * one to stop the Quarkus application
 * one to stop the Quarkus remote debugger.

**Comment by angelozerr** [comment]
> At first glance, it works.

Nice! Thanks for having tested. Just one question, which OS are you using?

**Comment by angelozerr** [comment]
@ArtemenkoAndrii since it seems Gradle debug is working for you, I merged the PR and you can install [nightly-builds](https://github.com/redhat-developer/intellij-quarkus?tab=readme-ov-file#testing-nightly-builds) which should contains this fix.

If you need more improvement, please create another issues. Thanks;
