### ISSUE TITLE
Application.properties validation does not show error when property with empty boolean or integer value is defined

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#132]
Empty value is acceptable for string variables, but not for integer or boolean variables.

- BOOLEAN VALUE VARIABLE: quarkus.debug.reflection=
- INTEGER VALUE VARIABLE: quarkus.http.port=

<img width="304" alt="Snímek obrazovky 2020-06-12 v 15 09 12" src="https://user-images.githubusercontent.com/43820055/84506039-015fad80-acbf-11ea-9d75-c611377c9535.png">

**Comment by jeffmaury** [comment]
Same behavior on VSCode or Eclipse so it's likely a microprofile-ls issue.
