### ISSUE TITLE
`ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon annoying error message

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#1321]
I keep seeing this in the Error log: 

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.redhat.devtools.intellij.quarkus.run.QuarkusDevActionGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.redhat.devtools.intellij.quarkus]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by fbricon** [comment]
This is already fixed with https://github.com/redhat-developer/intellij-quarkus/pull/1310

Please install the latest [nightly build](https://github.com/redhat-developer/intellij-quarkus?tab=readme-ov-file#testing-nightly-builds) (you will first need to install the latest [LSP4IJ nightly build](https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-nightly-builds))

**Comment by gastaldi** [comment]
Any chance to have an official release with this fix soon?

**Comment by angelozerr** [comment]
@gastaldi we plan to do a release of LSP4IJ and IJ Quarkus in 3 weeks. But please try the nightly build to give us feedback before the release.

**Comment by gastaldi** [comment]
Maybe it was a refresh problem, it didn't occur when I reopened the IDE, I'll wait until it happens again to report 👍🏻

**Comment by fbricon** [comment]
@gastaldi you've stumbled upon https://github.com/redhat-developer/intellij-quarkus/issues/1222. It happens when closing the current project and opening a different one, while IDEA is still running.
