### ISSUE TITLE
Invalid char(s) in expression. quarkus (9)

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#1325]
When creating a `@Scheduled` method in a Quarkus application like the following, the IDE complains with `Invalid char(s) in expression. quarkus (9)` when hovering the `cron` expression:

```java
@ApplicationScoped
@Startup
public class MavenCacheState {

    @PostConstruct
    @Scheduled(cron = "{quarkus.registry.cache.cron:*/10 * * * * ?}")
    void checkDbState() {
    }
}
```

**Comment by angelozerr** [comment]
I dont master the validation of cron expression.

I Wonder if there is the same problem with vscode-quarkus?

**Comment by gastaldi** [comment]
@angelozerr yes, I can confirm this also happens in vscode

<img width="529" alt="image" src="https://github.com/redhat-developer/intellij-quarkus/assets/54133/a83bb68a-ed42-4cb5-8181-823aec67099b">

**Comment by fbricon** [comment]
This is caused by the cron validator not supporting variable injection:

https://github.com/redhat-developer/intellij-quarkus/blob/25ce1d6e9172bfcd753e18ef8403e6e95629fa73/src/main/java/com/redhat/microprofile/psi/internal/quarkus/scheduler/SchedulerUtils.java#L74-L89

**Comment by fbricon** [comment]
My bad the error seems to come from 

https://github.com/redhat-developer/intellij-quarkus/blob/25ce1d6e9172bfcd753e18ef8403e6e95629fa73/src/main/java/com/redhat/microprofile/psi/internal/quarkus/scheduler/SchedulerUtils.java#L117-L120
