### ISSUE TITLE
Newly created project shows "Non-managed pom.xml file found" warning

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#133]
- create new quarkus project with minimum extensions, see the warning in the right bottom of the screen
- noticeable fact is that the project can be built from terminal without any issue (**./mvnw compile quarkus:dev** command)

<img width="412" alt="Snímek obrazovky 2020-06-12 v 15 25 02" src="https://user-images.githubusercontent.com/43820055/84507473-2c4b0100-acc1-11ea-8fce-a2977ed12aa2.png">

**Comment by jeffmaury** [comment]
I cannot reproduce it. Maybe a timing issue as the Maven project is being built. Is your Maven project correctly setup after all IJ tasks are run ?

**Comment by zcervink** [comment]
@jeffmaury yes, the maven project is without any issue. I haven't seen the issue last 2 days, maybe it appears rarely. And maybe it is just harmless warning you can close and the issue did not affect the functionality.
