### ISSUE TITLE
Resolve system properties/environment variables while browsing the `application.properties` values

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#1331]
It would be nice if the current System properties (eg. `user.name`) is resolved while browsing the `application.properties` values:

![image](https://github.com/redhat-developer/intellij-quarkus/assets/54133/87f2105d-54dd-4701-bc98-5ba38d6d4b24)

**Comment by angelozerr** [comment]
@gastaldi and what about completion on properties/environment variables?

**Comment by fbricon** [comment]
should we also get environment properties?

**Comment by gastaldi** [comment]
Probably yes, I am not sure how would that affect security-wise (eg. while doing presentations and your API key defined in an env var is displayed in the screen)

**Comment by fbricon** [comment]
we can maybe obfuscate *_KEY env vars

**Comment by fbricon** [comment]
I've got the beginning of something ;-) 
<img width="496" alt="Screenshot 2024-05-14 at 19 19 08" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/def0d49f-b094-47d9-9089-c3223b5dc89e">


but validation and completion still don't work

**Comment by angelozerr** [comment]
@gastaldi is it allowed to assign env value in properties file like

`user.name = FOO`

I mean should we have completion on user.name as property key?

**Comment by gastaldi** [comment]
Sure, that's allowed too

**Comment by angelozerr** [comment]
Thanks @gastaldi for your answer!
