### ISSUE TITLE
Formatting is broken when using  simple `{}`

### ISSUE THREAD

**Issue by ia3andy** [redhat-developer/intellij-quarkus#1345]
as an example try https://github.com/quarkusio/quarkus-web-lab/tree/main/solution/1-cms

Open src/main/resources/templates/Cms/index.html and reformat.
Remove the `{}` and it works:

https://github.com/redhat-developer/intellij-quarkus/assets/2223984/dd2312e0-b591-4719-b586-3bcb6b7946ec

**Comment by fbricon** [comment]
Can you reduce the example to the simplest qute template?

**Comment by ia3andy** [comment]
I won't have the time @fbricon sorry

**Comment by angelozerr** [comment]
I have no idea how IJ HTML formatter is working, but here a small sample:

```
<div class="left-bar d-flex justify-content-between">
    <div id="blog-editor" class="flex-grow-1 p-2">
        {#if currentBlogEntry}
                <form action="abc">
                </form>
        {/if}
    </div>
</div>
```

after formatting:

```
<div class="left-bar d-flex justify-content-between">
<div id="blog-editor" class="flex-grow-1 p-2">
{#if currentBlogEntry}
    <form action="abc">
    </form>
{/if}
</div>
</div>

```

**Comment by angelozerr** [comment]
Here a version without HTML attribute and qute expression:

```
<div>
    <div>
        {#if}
            <form>
            </form>
        {/if}
    </div>
</div>
```

after formatting:

```
<div>
<div>
    {#if}
        <form>
        </form>
    {/if}
    </div>
    </div>
```
