### ISSUE TITLE
Bump intellij-common-ui-test-library version

### ISSUE THREAD

**Issue by olkornii** [redhat-developer/intellij-quarkus#1348]
Bump intellij-common-ui-test-library after PR (https://github.com/redhat-developer/intellij-common-ui-test-library/pull/239) merge and next library release.

**Comment by mohitsuman** [comment]
@olkornii any update on this ?

**Comment by olkornii** [comment]
@mohitsuman 
No, waiting for https://github.com/redhat-developer/intellij-common-ui-test-library/issues/266

**Comment by mohitsuman** [comment]
okay, we should be good now as that issue is not merged.

**Comment by olkornii** [comment]
There is an issue in new library version: https://github.com/redhat-developer/intellij-common-ui-test-library/issues/284 
I would like to wait for the fix.

**Comment by mohitsuman** [comment]
@olkornii I see the https://github.com/redhat-developer/intellij-common-ui-test-library/issues/284 is now closed, how does this affect the current issue ?

**Comment by olkornii** [comment]
Hi @mohitsuman , looks like library is ready. I'll discuss it with my team and try to find some time to finish this issue.

**Comment by mohitsuman** [comment]
@olkornii Let's try to get this done before the next release and keep me posted with the timeline.

**Comment by olkornii** [comment]
@mohitsuman I discussed it with my team. The latest version of the library has not been released yet. The release is scheduled for Friday. So I would like to do this bump after release (next week) as actual release contains a bug.

My new team have a release coming up next week, so I may be involved in process. Because of that I might delay that bump, we'll see.

**Comment by angelozerr** [comment]
> Let's try to get this done before the next release and keep me posted with the timeline.

@mohitsuman it is not sure but perhaps I will do a bug fix release this week since the debug gradle project doesnt work.
