### ISSUE TITLE
Newly created Quarkus project has marked artifactId' and version' value in the pom.xml with red color

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#135]
I am not sure if this is a Quarkus issue, but I have decided to report it anyway. Newly created Quarkus project with minimum extensions has marked some values in the pom.xml with red color. I looks like the **maven-failsafe-plugin** has issues to be recognized while the **maven-surefire-plugin** is recognized without any issue:

<img width="877" alt="Snímek obrazovky 2020-06-17 v 16 21 16" src="https://user-images.githubusercontent.com/43820055/84910178-d8705b80-b0b6-11ea-8362-08ead0fcefc9.png">

**Comment by jeffmaury** [comment]
Cannot reproduce
