### ISSUE TITLE
Completion for props in application.properties is not honors annotation @WithName in some cases

### ISSUE THREAD

**Issue by lasteris** [redhat-developer/intellij-quarkus#1353]
I've described the problem more detailed in application.properties of my reproducer.

Here is reproducer sample: https://github.com/lasteris/quarkus-reproducer-idea-plugin
IntelliJ IDEA 2024.1.2 (Ultimate Edition)

Below is picture how does it look for me:
![изображение](https://github.com/redhat-developer/intellij-quarkus/assets/12238731/dc7bfc84-5c03-40c2-9630-74390be96722)

But obviously, row 14 should be highlighted, not 9.

**Comment by angelozerr** [comment]
I think this highlighting is managed by IJ himself but I dont master this feature.

I need to investigate your issue

**Comment by lasteris** [comment]
But if it IJ itself, then how it understands relationship of application.properties key to field of some Configuration interface.
And moreover, for custom interfaces this is working as it should. I don't understand what really in quarkus-cxf config so different

**Comment by angelozerr** [comment]
Are you using Quarkus support from Jetbrains?

**Comment by lasteris** [comment]
I've opened now plugins and saw, 
![изображение](https://github.com/redhat-developer/intellij-quarkus/assets/12238731/9d1ec6e7-2cfd-43fc-9420-2ddf54113a71)
so, as i understood correctly, i need to remove Jetbrains plugin and install Quarkus Tools of RedHat ?

**Comment by lasteris** [comment]
@angelozerr Thank, you, i m feeling me so dumb now. Your plugin works perfectly. I' even did not know that there is 2 plugins.
I think issue we should close

**Comment by angelozerr** [comment]
> @angelozerr Thank, you, i m feeling me so dumb now. Your plugin works perfectly. I' even did not know that there are 2 plugins.
> I think issue we should close

Glad you have fixed your issue by installing our IJ Quarkus plugin.

Hope you will enjoy with it.
