### ISSUE TITLE
Quarkus Dev Mode is having trouble running main module by using `Gradle with Kotlin DSL`

### ISSUE THREAD

**Issue by hjbolide** [redhat-developer/intellij-quarkus#1374]
Hi team,

After upgrading to plugin 2.0.0, the dev mode launcher seems to have issue running the main module, please see attached screenshot:
![Screenshot 2024-08-28 at 9 36 13 AM](https://github.com/user-attachments/assets/9172bd76-7f28-4882-99f7-49cd865b4230)

This is a fresh kotlin project generated by quarkus cli.

Old projects also suffered from the same.

Thanks,
Charles

**Comment by angelozerr** [comment]
What is the issue?

The name of the run config which ends with .main?

Have you this problem with previous version ?

**Comment by hjbolide** [comment]
Hi @angelozerr ,

Please see the bottom of the screenshot where it says "Quarkus Configuration: Can't find a tool to process the module" with exclamation mark at the front.

The configuration does not run, no matter how many times I tried to press the Run button.

I had no issue with the previous version of Quarkus Tools plugin, this issue only started to appear last night after I upgraded the plugin to 2.0.0.

I have tried in both Linux and Macos.

**Comment by angelozerr** [comment]
I have tested with my Windows OS and IJ 2024.1 and it works great.

@fbricon have you the same problem with your Mac OS?

**Comment by angelozerr** [comment]
@hjbolide  which version of IJ are you using?

**Comment by angelozerr** [comment]
Ok thanks for your feedback.

Could you share your project please.

**Comment by hjbolide** [comment]
See:
https://github.com/hjbolide/code-with-quarkus

Bare bone project straight out of quarkus-create

**Comment by hjbolide** [comment]
I have just bumped my Ultimate Edition to IntelliJ IDEA 2024.1.6 (Ultimate Edition) and issue is still there.

**Comment by angelozerr** [comment]
After importing your project, I have indeed the same problem than you.

I though it worked because the generated project contains a Java class and not a kotlin class although I have select BuildTool `Gradle with Kotlin DSL` (same problem with https://code.quarkus.io/ and with IJ Quarkus

![image](https://github.com/user-attachments/assets/15a76c15-f6f6-4547-a68a-9c8b5a400a86)

How have you generate your project?

**Comment by hjbolide** [comment]
I used quarkus cli to create my project: 

`quarkus create —-kotlin -—gradle`

the older project I have created a few weeks ago with the same command.

**Comment by hjbolide** [comment]
Hey @angelozerr ,

I've installed the snapshot build of the plugin you linked and the issue went away.

Thank you very much!

**Comment by angelozerr** [comment]
@hjbolide please wait.

As it is a major issue, we decide with @fbricon to create a new release (hope today).

@fbricon is working on that.

**Comment by angelozerr** [comment]
@hjbolide you can install now 2.0.1 release

**Comment by hjbolide** [comment]
Thanks @angelozerr and @fbricon for promptly addressing the issue.
