### ISSUE TITLE
REST endpoint code vision hint is not resolving a `public static final` and `quarkus.rest.path` parameter

### ISSUE THREAD

**Issue by FreifeldRoyi** [redhat-developer/intellij-quarkus#1393]
![Screenshot 2024-10-07 at 18 06 52](https://github.com/user-attachments/assets/c7052f21-53be-438f-b850-9e9d974b25d0)

As shown in the attached image:
1. The REST endpoint is given as a `public static final` field and is not resolved. Pressing the link will resolve to the same faulty url. 
2. I have set up a `quarkus.rest.path` variable in `application.properties` and it is not being resolved.

I have opened a [similar bug](https://github.com/quarkusio/quarkus/issues/43735) for something that might be related

**Comment by FreifeldRoyi** [comment]
Sure np. Thank you for the maintenance work

**Comment by angelozerr** [comment]
@FreifeldRoyi please follow PR https://github.com/redhat-developer/intellij-quarkus/pull/1396

**Comment by angelozerr** [comment]
@FreifeldRoyi if you want to try this feature before waiting the release:

 * install LSP4IJ 0.7.0 nighty build, see https://github.com/redhat-developer/lsp4ij?tab=readme-ov-file#testing-nightly-builds
 * install IJ Quarkus nighty build see https://github.com/redhat-developer/intellij-quarkus?tab=readme-ov-file#testing-nightly-builds

And please give me feedback if it works for you.

Please note that if you define a new value for `quarkus.rest.path` in application.properties, it will not refresh code vision. You will need to add a space for instance in your Java editor to refresh it.

Please create an issue with this problem.
