### ISSUE TITLE
Proposed code templates take precedence from everything in code

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#152]
After installing the plugin, when you type `Ctrl+Space` in any Java class in your code, the code templates proposed by the plugin take precedence from the correct choices. 

![Screenshot-from-2020-06-26-11-36-00](https://user-images.githubusercontent.com/54133/85879573-fde51f80-b7b0-11ea-8fbb-e81ab709513a.png)

**Comment by wjglerum** [comment]
Encountered the same behavior here. I like the plugin and hopefully this can be fixed quickly. Disabled the plugin for now.
