### ISSUE TITLE
Repolink in GradleImportingTestCase is not working

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#166]
See the following link - the link to repo is not working (at the beginning I thought that it needs update to https, but it looks like the whole subdomain is death):
- https://github.com/redhat-developer/intellij-quarkus/blob/master/intellij-community/plugins/gradle/testSources/org/jetbrains/plugins/gradle/importing/GradleImportingTestCase.java#L186

**Comment by jeffmaury** [comment]
Use only by JetBrains CI system

**Comment by zcervink** [comment]
@jeffmaury ok, I understand now. Can you please close this issue, I do not have permissions. Thank you.
