### ISSUE TITLE
Possible security issue: hard-coded password

### ISSUE THREAD

**Issue by akondasif** [redhat-developer/intellij-quarkus#170]
Greetings, 

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of hard-coded passwords. According to [CWE](https://cwe.mitre.org/data/definitions/259.html), "A hard-coded password typically leads to a significant authentication failure that can be difficult for the system administrator to detect." 

Hopefully, you agree and will fix it.

Source: https://github.com/redhat-developer/intellij-quarkus/blob/master/projects/maven/using-vertx/src/main/resources/application.properties

**Comment by jeffmaury** [comment]
This is about a test project and does represent a fake non existent password
