### ISSUE TITLE
Unknown property warning for quarkus.container-image properties

### ISSUE THREAD

**Issue by cameronprater** [redhat-developer/intellij-quarkus#177]
With the `quarkus-container-image-jib` dependency in the project's pom.xml, unknown property warnings appear for each of the quarkus.container-image properties in application.properties.

![image](https://user-images.githubusercontent.com/40479627/86880721-18759d80-c0bb-11ea-901e-ffff7c6ac6ff.png)

**Comment by jeffmaury** [comment]
See https://github.com/redhat-developer/quarkus-ls/issues/341
