### ISSUE TITLE
Insecure coding pattern: Missing default case in switch statements 

### ISSUE THREAD

**Issue by paser4se** [redhat-developer/intellij-quarkus#184]
Greetings, 

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found that your code does not have a default case in the switch statement. According to the Common Weakness Enumeration organization, this is a security weakness. See the link https://cwe.mitre.org/data/definitions/478.html

Source: https://github.com/redhat-developer/intellij-quarkus/blob/master/src/main/java/com/redhat/devtools/intellij/quarkus/search/PropertiesManager.java and https://github.com/redhat-developer/intellij-quarkus/blob/master/src/main/java/com/redhat/devtools/intellij/quarkus/javadoc/JavaDoc2HTMLTextReader.java

Fix: Fix #182 and #183 

I am interested to know if you agree with the findings. Any feedback is appreciated.

**Comment by fbricon** [comment]
These were fixed about 3 years ago. Closing.
