### ISSUE TITLE
Intellij IDEA starts hanging after update Quarkus Tools plugin to v1.0.2.24

### ISSUE THREAD

**Issue by fabasoad** [redhat-developer/intellij-quarkus#185]
I've updated Quarkus Tools plugin to the latest version (1.0.2.24 currently) and after that Intellij IDEA just hangs after I start typing something. It happens always. Once I disable this plugin Intellij IDEA starts working correctly.

Please let me know if you need any other information.

**Comment by vitorpavanelli** [comment]
I'm also having the same issue as @fabasoad .

**Comment by jeffmaury** [comment]
Can you specify the context or take a dump of the thread stacks when that happens. 

9f5ee709d18d594d0a8dacc543effdcd790d258f is supposed to have that fixed.

**Comment by vitorpavanelli** [comment]
I had to disable the plugin so I will enable it again and when the issue happens I will try to get the details.

**Comment by fabasoad** [comment]
Will do the same. I'll back to you once I will have any results.

**Comment by fabasoad** [comment]
It happened again. I've made a thread dump of Intellij IDEA by VisualVM:
https://drive.google.com/file/d/1cQIeahJh6t_N9c7uQy2ojn8H5P8ROVO6/view?usp=sharing

**Comment by vitorpavanelli** [comment]
[threadDumps-freeze-20200721-210815-IU-201.8538.31.zip](https://github.com/redhat-developer/intellij-quarkus/files/4959999/threadDumps-freeze-20200721-210815-IU-201.8538.31.zip)

I have taken the logs from within IntelliJ -> Help -> Collect Logs... I saw some errors in there regarding the plugin when auto-completion is triggered. It seems it is trying to access something already locked, for example, I was typing in a class "String".. but it didn't even completed... it was like "Str" then froze. So it isn't only for quarkus, but overall. I can't tell exactly when it happens, but I can tell it is related to offering suggestion when typing. After the plugin is disabled, IntelliJ doesn't freeze anymore. Thank you for taking a look at it.

**Comment by vitorpavanelli** [comment]
> Can you specify the context or take a dump of the thread stacks when that happens.
> 
> [9f5ee70](https://github.com/redhat-developer/intellij-quarkus/commit/9f5ee709d18d594d0a8dacc543effdcd790d258f) is supposed to have that fixed.

Please, when will it be released this fix 9f5ee70?

**Comment by fabasoad** [comment]
I have exactly the same behavior as @vitorpavanelli has.

**Comment by jeffmaury** [comment]
This change is part of the 1.0.2 so I'm looking at another problem

**Comment by vitorpavanelli** [comment]
> This change is part of the 1.0.2 so I'm looking at another problem

ok! thank you

**Comment by jeffmaury** [comment]
Can you specify the OS and IJ edition and version your are using as I installed Quarkus Tools on my IJ Ultimate I'm using for dev purposes and never got it

**Comment by vitorpavanelli** [comment]
> Can you specify the OS and IJ edition and version your are using as I installed Quarkus Tools on my IJ Ultimate I'm using for dev purposes and never got it

I'm on Windows 10 and using latest IntelliJ Ultimate. The issue happens after some time, it doesn't happen right away. At some point when coding it just freezes everything.

**Comment by jeffmaury** [comment]
I think I found the cause. Validating the patch and a new release will be out soon.

**Comment by vitorpavanelli** [comment]
Awesome! thank you very much.

**Comment by fabasoad** [comment]
@jeffmaury Still reproduces on my machine :(

**OS:**
MacOS Catalina 10.15.6

**Intellij IDEA:** 
IntelliJ IDEA 2020.1.3 (Ultimate Edition)
Build #IU-201.8538.31, built on July 7, 2020
Runtime version: 11.0.7+10-b765.64 x86_64

**Java:**
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

**VisualVM Thread dump:**
https://drive.google.com/file/d/1GJiUr4_8a02T0zRrmdfoT9fJoEmLvy07/view?usp=sharing

**Comment by fabasoad** [comment]
Forgot to mention:

**Quarkus version:** 1.6.1.Final
**Quarkus plugin version:** 1.0.3.39

**Comment by stephenc** [comment]
Affecting me on 2020.2

**Comment by jeffmaury** [comment]
@vitorpavanelli @fabasoad @stephenc I just pushed a new version 1.0.4.45 that should fix the problem. Let me know if you still have issues

**Comment by fabasoad** [comment]
Using 1.0.4.45 last few days. Works for me 👍 Thank you!
