### ISSUE TITLE
Unable to add new Quarkus Run/Debug Configuration

### ISSUE THREAD

**Issue by OliverSoria** [redhat-developer/intellij-quarkus#206]
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1965M
Cores: 8
Non-Bundled Plugins: Lombook Plugin, com.redhat.devtools.intellij.quarkus
Windows version: 2004 (Compilation SO 19041.450)

I can´t find the way to add a new Quarkus Run/Debug Configuration, it used to be there in older versions:

Before:
![imagen](https://user-images.githubusercontent.com/15372610/90607441-d2861c00-e1c6-11ea-8243-1ec857aef706.png)

Now:
![imagen](https://user-images.githubusercontent.com/15372610/90607214-8cc95380-e1c6-11ea-9b97-62e83d9c3373.png)

**Comment by jeffmaury** [comment]
This feature is not part of this plugin
