### ISSUE TITLE
annotation.properties should be treated as case insensitive

### ISSUE THREAD

**Issue by MarcusBiel** [redhat-developer/intellij-quarkus#208]
https://quarkus.io/guides/quartz

States:
quarkus.quartz.store-type=jdbc-cmt

Which throws an error in the most recent version of IntelliJ idea with Quarkus support:
Cannot resolve field 'jdbc-cmt' in enum 'io.quarkus.quartz.runtime.StoreType'

quarkus.quartz.store-type=JDBC_CMT

works - but the application.properties should be case insensitive according to:
https://github.com/quarkusio/quarkus/issues/11463

**Comment by jeffmaury** [comment]
Are you using Quarkus Tools or the Quarkus support from JetBrains as I can't reproduce in Quarkus Tools

**Comment by MarcusBiel** [comment]
I assume the later - I am just using Intellij professional out of the box.

**Comment by jeffmaury** [comment]
So you should report it on the issue system.
