### ISSUE TITLE
Newly created quarkus project cannot be built using maven

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#209]
The **compile, test, package, verify** and **install** maven targets shows the following error when invoked from the Maven Tool Window:

`Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project code-with-quarkus: Fatal error compiling`

**Here is an image of the Maven Tool Window:**

<img width="413" alt="img" src="https://user-images.githubusercontent.com/43820055/90896383-d03ce100-e3c3-11ea-8189-357de0d16bcd.png">

**Comment by harshmadhani** [comment]
I faced the same error when creating a project through the IntelliJ plugin. Is the issue resolved or are there any plans for the same?

**Comment by zcervink** [comment]
@harshmadhani I tested the updated version of the plugin few moment ago. The issue seems to be resolved. @jeffmaury I suggest to close this issue.

**Comment by jeffmaury** [comment]
I tested it on IJ Ultimate 2020.2 and Quarkus Tools 1.1.0.57 (latest release) and got not problem. Can you make sure that the Java SDK attached to the project is a Java11 one (required now by Quarkus)

**Comment by harshmadhani** [comment]
@jeffmaury @zcervink Thanks, when I ran the build from the Maven Tool window, it works fine for me.

**Comment by zcervink** [comment]
@jeffmaury I have tested it several times (during implementing the UI tests), the issues is now resolved, I suggest to close this issue.

**Comment by zcervink** [comment]
@jeffmaury I have retested this issue again, the issue is now resolved, I think you can close it.
