### ISSUE TITLE
application.properties configuration value equivalence with - & _

### ISSUE THREAD

**Issue by evialle** [redhat-developer/intellij-quarkus#220]
When declaring in application.properties:

`quarkus.oidc.application-type=web-app`, I have the following error:
![image](https://user-images.githubusercontent.com/1042980/91639814-6bb00080-ea19-11ea-913b-60bf03058f1d.png)

The quarkus code declares that property potential _web-app_ is with a `_` and not a `-` 
![image](https://user-images.githubusercontent.com/1042980/91639886-06104400-ea1a-11ea-9c1b-d662c1dd6626.png)

Quarkus developper says that properties values having `_` &` - `are equivalent: https://github.com/quarkusio/quarkus/issues/11586

I would expect no error displayed, when using a - instead a _ with a property in intellij, and declare my file application.properties valid.

**Comment by jeffmaury** [comment]
I think you are using Quarkus tooling from JetBrains and not Quarkus Tools. See #208
