### ISSUE TITLE
Lots of Java files does not have updated year in the licence

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#236]
The are several Java files that does not have year 2020 included in the licence (they have for example 2019 instead of the 2019-2020 interval).

**Comment by jeffmaury** [comment]
Policy for this project is to have the year represents the creation year of the file.
Any example

**Comment by zcervink** [comment]
@jeffmaury Thank you very much for this information. I think you can close this issue now.
