### ISSUE TITLE
Automate UI test that checks if the quarkus runtime is up to date

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#266]

**Comment by jeffmaury** [comment]
My initial idea was to have a GitHub workflow that will do:
- retrieve the latest Quarkus version from Maven Central
- compare it to the version implemented in the repository
- if they don't match
  - apply the changes in the repo
  - create a pull request

**Comment by zcervink** [comment]
@jeffmaury That would be better than to create and manage an automated test.

**Comment by zcervink** [comment]
@jeffmaury I saw the workflow PR has been merged, I suggest to close this issue, because we are probably not going to need that test (the workflow should make the whole work, than there is no need for UI testing and analyzing the results manually). Or do you think there should be a UI tests together with the workflow?
