### ISSUE TITLE
Error in artifact version when creating a new project

### ISSUE THREAD

**Issue by tqvarnst** [redhat-developer/intellij-quarkus#29]
When I create a new Quarkus module (as a new project) it is generated with `<verison>/hello</version>` instead of `<version>1.0.0-SNAPSHOT</version>` in the pom.xml.

Environmental details: 
```
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 27, 2019
Licensed to Thomas Qvarnström
Subscription is active until April 25, 2020
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: BashSupport, com.intellij.plugins.html.instantEditing, com.oliverlockwood.plugins.jenkinsfile, com.redhat.devtools.intellij.quarkus, io.protostuff.protostuff-jetbrains-plugin, org.asciidoctor.intellij.asciidoc, org.intellij.scala, org.jetbrains.plugins.vue, training
```

**Comment by tqvarnst** [comment]
I believe the error his here: https://github.com/redhat-developer/intellij-quarkus/blob/31fbf6b36d33e36cef35ce23047cb2c4d4b610af/src/main/java/com/redhat/devtools/intellij/quarkus/module/QuarkusModuleBuilder.java#L142 which would override the version with the path.

**Comment by jeffmaury** [comment]
Yes I just caught the bug yesterday reviewing my code. Fixing LSP related issues and I will push a new release by end of day. Should be online early next week.

**Comment by thesteve0** [comment]
Still present in 0.0.1.12

**Comment by thesteve0** [comment]
NVM - just got the update to 0.0.3 in intellij
