### ISSUE TITLE
Building LSP support with lsp4intellij

### ISSUE THREAD

**Issue by gayanper** [redhat-developer/intellij-quarkus#294]
Is there a possibility that this tooling can use https://github.com/ballerina-platform/lsp4intellij which is a complete LSP integration to support Language Servers in intellij.

**Comment by jeffmaury** [comment]
This plugin was based on the previous fork, the design has several flaws and maintenance was not sustainable.

**Comment by gayanper** [comment]
@jeffmaury you mean the plugin this repo represents or the lsp4intellij plugin?

**Comment by jeffmaury** [comment]
The plugin you mentioned

**Comment by gayanper** [comment]
@jeffmaury so does jboss have better lsp integration for symbols, completions and diagnostics on Language servers?

**Comment by jeffmaury** [comment]
This plugin has its own LSP implementation derived from LSP4E but only what's required is implemented.
We may in a short future extract it in a separate plugin but that would require implementing more LSP stuff

**Comment by gayanper** [comment]
Looking forward too. Even though lsp4e was based on fork from a scala implementation. The whole plugin is changed into java and some of the implementation has been changed to support language servers like sts4 and ballerina. May you could evaluate the latest and contribute what you think should be change and avoid starting another spin for intellij. Just a suggestion

**Comment by jeffmaury** [comment]
When I started the LSP implementation, it did not exist yet. And as the design is the same as the original one, the design is also broken. What do you want this plugin to use it ?

**Comment by gayanper** [comment]
I was more interested broadening the consumer of the lsp4intellij plugin since IJ lacks support for LSP and DAP. And also evaluate the plugin with other language servers. 

But as you say if there are issues, i think it would be nice to have a better implementation from jboss since if i remember jboss was part of lsp4e implementation as well.

**Comment by gayanper** [comment]
@jeffmaury if you could move the lspij code to to different github repo, may be we can make it a library to be used by other projects like sts4 to give intellij support. I’m maintaining a sts4 IJ implementation so i would be able to use and provide PRs enhance this.

**Comment by jeffmaury** [comment]
It's a medium / long term goal and It's not design as a library use ballerina for that
