### ISSUE TITLE
New Java Project wizard shows two "Quarkus" options 

### ISSUE THREAD

**Issue by harshmadhani** [redhat-developer/intellij-quarkus#303]
**Steps to produce** : 

1. Open the 'New Project' wizard
2. Select 'Java' project
3. There are two options under 'Additional Libraries and Frameworks' as shown below :  

![image](https://user-images.githubusercontent.com/1668599/99882147-5b887580-2c44-11eb-8ebc-c155f004f883.png)

Quarkus tools plugin version - 1.2.0.71 
IDE - IntelliJ IDEA 2020.2.3 (Community Edition)

**Comment by zcervink** [comment]
@harshmadhani This is a duplicit issue - https://github.com/redhat-developer/intellij-quarkus/issues/89 @jeffmaury can you please close this issue as duplicit?
