### ISSUE TITLE
Workflow for updating runtime version skips version 1.10.5.Final

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#326]
- last PR created is for update to version 1.10.4.Final:
   - https://github.com/redhat-developer/intellij-quarkus/pull/319
- possible reason:
   - the workflow skips the beta version, so maybe the 1.10.5.Final version and the following 1.11.0.Beta1 beta version appears one after the second with a short range of time between each release - the workflow created PR to update to 1.10.4.Final and next time it has found 1.11.0.Beta1 as the newest runtime available (and it has skipped it because it is a beta version)

**Comment by jeffmaury** [comment]
It was not skipped but closed by myself because of beta.
See https://github.com/redhat-developer/intellij-quarkus/pull/323

**Comment by zcervink** [comment]
@jeffmaury I think this issue should be closed.
