### ISSUE TITLE
Add the "Gradle with Kotlin DSL" build tool option to the plugin

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#383]
Quarkus webpage offers the "Gradle with Kotlin DSL" build tool option (https://code.quarkus.io/?b=GRADLE_KOTLIN_DSL):

<img width="433" alt="Snímek obrazovky 2021-03-24 v 9 29 27" src="https://user-images.githubusercontent.com/43820055/112278783-7961f780-8c83-11eb-9672-5a917437bcf9.png">

The plugin does not offer that option:

<img width="300" alt="Snímek obrazovky 2021-03-24 v 9 29 57" src="https://user-images.githubusercontent.com/43820055/112278834-8848aa00-8c83-11eb-967c-936179853e80.png">

**Comment by jeffmaury** [comment]
Fixed by f199c767b861de8aeba2122c1dea1cf1e3aaaaa3

**Comment by MartinX3** [comment]
Please create a gradle 1.6.1 with this bugfix.
