### ISSUE TITLE
Create shared library for UI testing of IntelliJ Idea Plugins

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#395]
- repository will be located in the redhat-developer account (temporarily in my repository before it is ready and approved to move to redhat-developer)
- library is a gradle project
- library can be used as dependency in other gradle projects (gradle can generate pom.xml and make it maven artifact)
- library contains:
   - fixtures for several common IntelliJ Idea wizards and UI elements
   - static utilities for common operations and actions in the IDE

Several future content of the library is already created here (and will be moved to this library):
- https://github.com/redhat-developer/intellij-quarkus/tree/main/src/it/java/org/jboss/tools/intellij/quarkus

**Comment by jeffmaury** [comment]
There's already intellij-common for that. So I would suggest:
- use this repository with a different qualifier
- use a new repository with a similar name (intellij-common-uitests ?)

**Comment by zcervink** [comment]
@jeffmaury I have discussed the 'repository name' issue with Jan and Josef, we have decided to name it **intellij-common-ui-test-library** for now:

- https://github.com/zcervink/intellij-common-ui-test-library

**Comment by zcervink** [comment]
Shared library has been created: https://github.com/zcervink/intellij-common-ui-test-library.
Task completed, I close this issue.
