### ISSUE TITLE
Telemetry plugin was not installed with the Quarkus  plugin

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#398]
- I have tried to install the Quarkus plugin (last build from repo) into the new version of IntelliJ (2021.1) on 2 notebooks
   - on the older one (OS X 10.13.6), IntelliJ offers to install the dependencies:
![sni__mek_obrazovky_2021-04-19_v__12 25 30](https://user-images.githubusercontent.com/43820055/115221995-88b15500-a10a-11eb-8896-294333595309.png)

   - On the newer one (OS X 11.2.3), the dialog did not appear, just the error messages:
<img width="800" alt="Snímek obrazovky 2021-04-19 v 12 18 51" src="https://user-images.githubusercontent.com/43820055/115221023-87cbf380-a109-11eb-8830-00965d70e69f.png">
<img width="800" alt="Snímek obrazovky 2021-04-19 v 12 13 17" src="https://user-images.githubusercontent.com/43820055/115221011-85699980-a109-11eb-84f4-91db5644d8ff.png">

**Comment by angelozerr** [comment]
@sbouchet @adietish do you think we can close this issue?

**Comment by angelozerr** [comment]
I close this issue since it seems be fixed.
