### ISSUE TITLE
Add Qute support

### ISSUE THREAD

**Issue by agoncal** [redhat-developer/intellij-quarkus#415]
It would be nice to have Qute support in Intellij. Syntax highlighting, code completion...

**Comment by jeffmaury** [comment]
See https://github.com/redhat-developer/quarkus-ls/issues/176

**Comment by angelozerr** [comment]
For Syntax highlighting you can reuse our TextMate grammar at https://github.com/redhat-developer/vscode-quarkus/tree/master/language-support/qute

**Comment by jreznot** [comment]
Just for the record, IntelliJ IDEA 2021.3 Ultimate will include Qute support https://blog.jetbrains.com/idea/2021/10/intellij-idea-2021-3-eap-6-enhanced-http-client-kotlin-support-for-cdi-and-more/

![image](https://user-images.githubusercontent.com/1066152/140640618-f685b5cd-be2a-4591-ad2c-02b5db313af2.png)

**Comment by angelozerr** [comment]
Thanks @jreznot for your feedback! 

We are working on Qute Langage Server LSP for Eclipse IDE and vscode that we will able to integrate in IJ too.
