### ISSUE TITLE
pre select default extensions

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-quarkus#42]
he extensions model has the notion of default extensions. Such extensions should be pre selected when launching the wizard

**Comment by zcervink** [comment]
I also suggests to add the INCLUDED label to them as it is on quarkus.io web (not only check the checkbox):
<img width="217" alt="img" src="https://user-images.githubusercontent.com/43820055/82153573-8692a680-9868-11ea-9b6e-2859c542f47d.png">
