### ISSUE TITLE
lags while editing REST services with version 1.8.0

### ISSUE THREAD

**Issue by Shohou** [redhat-developer/intellij-quarkus#487]
I'm experiencing heavy lags while editing REST services (classes having methods with `@Path`) with version 1.8.0
If I downgrade to version 1.7.0 all lags are gone.
Editing any other files doesn't have this issue
my CPU is Core i7-9700K so it's not lack of power or memory (32Gb)
Originally was tested on Intellij idea Ultimate version 2021.2, and now checked with 2021.3 and issue is still there
Created two videos to demonstrate this
version 1.7.0 - https://youtu.be/fw4V_pGV7kY
version 1.8.0 - https://youtu.be/qvsq6KY9A8g

**Comment by Shohou** [comment]
I also think it is the same, closing as duplicate of #790

**Comment by angelozerr** [comment]
> I also think it is the same, closing as duplicate of https://github.com/redhat-developer/intellij-quarkus/issues/790

Indeed it is the same thing and it is a really annoying problem. @fbricon @jeffmaury we need to fix the issue because IMHO the Java editor is unusable. 

As InlayHint is not asynchrone, it means codelens must be computed fast and we must not check the server available when codelens are computed. There are 2 solutions:

 * remove the server available check, it means that URL codelens will be displayed even if the server is not started (is it annoying to have that?)
 * manage server available check in a Thread deamon.

What do you think about that?

**Comment by fbricon** [comment]
is there a way to disable codelenses?

**Comment by jeffmaury** [comment]
> > I also think it is the same, closing as duplicate of #790
> 
> Indeed it is the same thing and it is a really annoying problem. @fbricon @jeffmaury we need to fix the issue because IMHO the Java editor is unusable.
> 
> As InlayHint is not asynchrone, it means codelens must be computed fast and we must not check the server available when codelens are computed. There are 2 solutions:
> 
>     * remove the server available check, it means that URL codelens will be displayed even if the server is not started (is it annoying to have that?)
> 
>     * manage server available check in a Thread deamon.
> 
> 
> What do you think about that?

Remove that stupid test and check 🥲

**Comment by angelozerr** [comment]
> is there a way (preference setting) to disable codelenses?

no, please create an issue to LSP4MP to support this settings.

> Remove that stupid test and check 

done in PR https://github.com/redhat-developer/intellij-quarkus/pull/793

**Comment by fbricon** [comment]
> > is there a way (preference setting) to disable codelenses?
> 
> no, please create an issue to LSP4MP to support this settings.

turns out lsp4mp  already supports [`microprofile.tools.codeLens.urlCodeLensEnabled`](https://github.com/search?q=repo%3Aeclipse%2Flsp4mp%20urlCodeLensEnabled&type=code)

**Comment by angelozerr** [comment]
>turns out lsp4mp already supports [microprofile.tools.codeLens.urlCodeLensEnabled](https://github.com/search?q=repo%3Aeclipse%2Flsp4mp%20urlCodeLensEnabled&type=code)

Good catch! I forget that we have a settings for codelens. It would be nice to have an UI preferences which configure the MP LS with this preferences.

**Comment by angelozerr** [comment]
@Shohou I wonder which OS you are using?

Me i'm using Windows OS and I have the same problem than you, but @fbricon whois using Mac OS have not this problem.

**Comment by Shohou** [comment]
@angelozerr I'm on windows as well
