### ISSUE TITLE
Link to Quarkus Language Server in README is broken

### ISSUE THREAD

**Issue by gastaldi** [redhat-developer/intellij-quarkus#52]
It points to https://github.com/redhat-developer/quarkus-ls/tree/master/quarkus.ls which gives a 404

**Comment by KaenDagger** [comment]
ping @gastaldi for the PR

**Comment by zcervink** [comment]
@jeffmaury This issue has been fixed with the merged "Prepare for 1.0.0" (#147). I suggest to close this issue as well as the open PR.

**Comment by jeffmaury** [comment]
Fixed by 18343a040c6d3a20360d172ecc3970b7d2d661ac
