### ISSUE TITLE
new quarkus project wizard: Extension is only deselected when I click 3x

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-quarkus#638]
**Steps:**
1. EXEC: File > New > Project > Quarkus
2. EXEC: get to the extensions page
3. EXEC: select Web > RESTEasy Reactive
4. EXEC: deselect it

**Result:**
"RESTEasy Reactive" is not deselected. It only gets deselected when I click 3x

**Comment by fbricon** [comment]
fixed with #936
