### ISSUE TITLE
Quarkus version 0.17.0 when adding Framework support

### ISSUE THREAD

**Issue by sshaaf** [redhat-developer/intellij-quarkus#64]
Reproducing the issue:
1. Right click on already created project in the Project Explorer
2. Add Frame work support
3. Select Quarkus from the framework list
4. The dialog says "1 Jar will be downloaded ... Quarkus-0.17.0"
5. Also shows the following error Failed to download when clicked OK. 'http://central.maven.org/maven2/io/quarkus/quarkus-core/0.17.0/quarkus-core-0.17.0.jar':
central.maven.org

Environment: 
IntelliJ IDEA 2019.3.4 (Ultimate Edition)
Build #IU-193.6911.18, built on March 17, 2020

Is this the Quarkus version, that Quarkus tools tries to download for the project? should this be a newer version like 1.3.0.Final?

**Comment by zcervink** [comment]
@sshaaf this is a duplicate issue to this https://github.com/redhat-developer/intellij-quarkus/issues/71
I have already created PR and I have attached it to the other issue

@jeffmaury I have not permissions to make operations such like close duplicated issue, or link them using github. Can you please give me the permissions or mark this issue as duplicate?
