### ISSUE TITLE
Yellow warning underline on application.properties too hard to see

### ISSUE THREAD

**Issue by emmanuelbernard** [redhat-developer/intellij-quarkus#66]
![Screenshot 2020-04-06 at 16 34 32](https://user-images.githubusercontent.com/300760/78569896-88f2f100-7824-11ea-958c-aa65f286aa1e.png)

**Comment by angelozerr** [comment]
Since several version we use standard error style. I close this issue.

@emmanuelbernard if you don't like the new UI please reopen the issue.
