### ISSUE TITLE
Can't open big multi part project

### ISSUE THREAD

**Issue by wgresshoff** [redhat-developer/intellij-quarkus#676]
I have a rather big project with ~20 sub-projects inside. With the Quarkus plugin activated, the project will not open. When I deactivate the plugin everything works fine. 
IDE: IntelliJ IDEA Ultimate 2022.2.3
Quarkus Tools: 1.13.1.283
If you need the Sourcecode of my project I can upload a zipped version (it's placed in a private Gitlab instance).

**Comment by jeffmaury** [comment]
Can you join the IJ log file ?

**Comment by wgresshoff** [comment]
[idea.log](https://github.com/redhat-developer/intellij-quarkus/files/9927236/idea.log)

This is an actual log! Thanks for looking!

**Comment by wgresshoff** [comment]
Sorry, in the log there were some issues with our local Maven repository (wrong password). After fixing this problem there is no longer an issue!
