### ISSUE TITLE
clicking on a property in applciation.properties leads to cannot find declaration to go to

### ISSUE THREAD

**Issue by emmanuelbernard** [redhat-developer/intellij-quarkus#69]
![Screenshot 2020-04-06 at 16 44 29](https://user-images.githubusercontent.com/300760/78570948-ef2c4380-7825-11ea-8992-57fd30380a47.png)

**Comment by angelozerr** [comment]
It's because IJ Quarkus doesn't implement for the moment the LSP getPropertyDefinition managed by the MicroProfile Language Server.

@emmanuelbernard after our discussion, I'm glad that you find this feature helpful :)
