### ISSUE TITLE
Diagnostics are out of sync

### ISSUE THREAD

**Issue by evie-lau** [redhat-developer/intellij-quarkus#692]
The LSP4MP diagnostics info seems to lag behind the user changes, showing diagnostic info from a previous state of the document before the change.
Here, a Bulkhead value of `-1` does get underlined in red, but there is no hover info: 
![image](https://user-images.githubusercontent.com/689163/205326588-e9c0d678-594e-480f-8bc2-e694a6a0eec5.png)

Adding a second digit, the diagnostic info updates to show the previous error:
![image](https://user-images.githubusercontent.com/689163/205326424-2fc139b2-7969-4c82-b8f6-3bfcfd13a5f7.png)

When quickly entering a few more characters, a seemingly random number of changes get processed in the diagnostic update, but never seems to be fully up-to-date with the changes. In both the following cases, I started with `-12` and quickly added `1234` in one quick stroke.
![image](https://user-images.githubusercontent.com/689163/205326362-a35a6f8b-3787-44a6-828e-a5745c56b5f9.png)
![image](https://user-images.githubusercontent.com/689163/205326867-c308430c-3fbe-49e3-ad65-87a7c6389997.png)

When I highlight the entire value and fix it to something appropriate, the diagnostic for the old value still remains, while also keeping the red underline for the same number of characters in the previous error (you can see it extend to part of `public` a couple lines down):
![image](https://user-images.githubusercontent.com/689163/205328031-49652b0d-c1f4-4cb3-85d8-667b3a179818.png)

Environment info: 
Quarkus tools: 1.14.0.292
IntelliJ 2022.2.3
OS: Reproduced on both macOS 13.0.1 and Windows 10
Plugins downloaded: 
![image](https://user-images.githubusercontent.com/689163/205328396-20fe86dc-e59c-400a-bb7d-1ff6ce18f499.png)

**Comment by evie-lau** [comment]
We have a fix in OpenLiberty/liberty-tools-intellij#307, which fixed a timing issue for the diagnostics sync by moving all the logic into the `apply` step of the ExternalAnnotator.
While it doesn't seem like proper usage of the ExternalAnnotator methods, it does resolve the timing of `collectInformation` grabbing old diagnostic information before the diagnostics handler has finished updating with new info.

**Comment by angelozerr** [comment]
Thanks for your information.

I see your patch but IMHO 

 * validation update should be done in a ExternalAnnotator to create annotation 
 * code action should never called when validation process is done. Code action can be very expensive and they should call only when caret move but without change of document or when an error is hovered. It is the behavior of vscode.

If you see my PR Im trying to implement this idea but it doesnt work correctly for the moment. Code action on hover is de synchronisés, you need to hover twice. The carte change when user is typing should not consume Code action

**Comment by angelozerr** [comment]
@evie-lau I suggest that you apply this patch on your side. This PR fixes validation but it starts fixing quick fix which are very slow. I will create another PR to continue to improve performance of code actions.
