### ISSUE TITLE
State of error in application.properties is fubar

### ISSUE THREAD

**Issue by emmanuelbernard** [redhat-developer/intellij-quarkus#70]
It claims errors where there are none and they do look weird.

![Screenshot 2020-04-06 at 16 45 30](https://user-images.githubusercontent.com/300760/78571167-30bcee80-7826-11ea-8540-8932bad7ed41.png)

**Comment by angelozerr** [comment]
It seems it is again a problem with editor synchronization with LSP language server fixed in https://github.com/redhat-developer/intellij-quarkus/pull/778

Please wait the new release (which will come doon) which have this fix.

Please reopen the issue if you encounter again the problem.
