### ISSUE TITLE
Access the artifact repositories via HTTPS 

### ISSUE THREAD

**Issue by psrna** [redhat-developer/intellij-quarkus#72]
HTTP access for maven central is disabled, thus Quarkus download not working.

https://www.alphabot.com/security/blog/2020/java/Your-Java-builds-might-break-starting-January-13th.html

**Comment by odockal** [comment]
This will also probably means to update https://github.com/redhat-developer/intellij-quarkus/blob/b16df48a4fed94e32dde19308002b944047efce8/src/main/resources/quarkus.xml#L5 to use https://repo1.maven.org/maven2/

**Comment by zcervink** [comment]
@psrna @odockal I have already fixed this issue when I upgraded the quarkus-core to the newest version. PR has been merged today and issue is closed - https://github.com/redhat-developer/intellij-quarkus/issues/71

What about to close this issue too?

**Comment by jeffmaury** [comment]
Closed by #5c547f6c82c1b3402a718b232d35b55ff6ab8808
