### ISSUE TITLE
Quarkus Tools significantly increases startup time for Intellij

### ISSUE THREAD

**Issue by dupliaka** [redhat-developer/intellij-quarkus#733]
Hello, 
I noticed that Quarkus Tools slows down start up of IntelliJ by more then 2.5 m
I didn't have that before the update of the plugin to 1.15.
Could you please check that?

IntelliJ idea 2022.3.1
Quarkus Tools for IntelliJ 1.15.0.308
Fedora Linux 37

**Comment by tmulle** [comment]
I also have the same issue when I try to open a single IDEA instance.
If I try to open another quarkus project in a "New Window" the IDE hangs and I have to kill it.

Removing the plugin from the `~/Library/Application Support/JetBrains/IntellijIdea2022.2/plugins/Quarkus Tools` folder allows IDEA to start up fast again, but I lose the plugin support.

Reinstalling it causes the same issue..

I'm on OS X Ventura 13.1 with IntelliJ IDEA 2022.2.2 (Ultimate Edition)
