### ISSUE TITLE
Update Gradle version to 6.3

### ISSUE THREAD

**Issue by koentsje** [redhat-developer/intellij-quarkus#76]

**Comment by jeffmaury** [comment]
What is the rationale for using a non stable version ?

**Comment by koentsje** [comment]
I am trying to get this plugin in a bit of a better shape but I run into a ton of issues and so I decided to start with making sure the Gradle is up to date... 
I didn't know this release was that unstable, it is a RC after all. But my bad, I can update it to 6.3 as well if you prefer that.
