### ISSUE TITLE
Improve completion with snippet support

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/intellij-quarkus#786]
Today completion for Qute and application.properties doesn't support snippet.

We should support it.

**Comment by turkeylurkey** [comment]
I added some code to handle certain variable substitution in https://github.com/OpenLiberty/liberty-tools-intellij/pull/383 .

**Comment by angelozerr** [comment]
Thanks @turkeylurkey for your feedback. I think I will rewrite this cmpletion support to support snippet (in IJ I think it is called template) to have the same feature than vscode https://github.com/redhat-developer/vscode-quarkus/blob/master/docs/qute/TemplateSupport.md#completion-for-qute-section

**Comment by angelozerr** [comment]
> I added some code to handle certain variable substitution in https://github.com/OpenLiberty/liberty-tools-intellij/pull/383 .

I have seen your patch and I found the existing code was very hard to understand with those all substring and it is impossible to write some tests. It is the reason why I decided to write a mini parser like SAX parser to parse a snippet content and handle the text, tabstop, placeholder, etc content exactly like SAX handler. 

You can see a sample test at https://github.com/redhat-developer/intellij-quarkus/pull/1006/files#diff-0bb3872d4ddbfc4f201198c61cd6a9afa8741ab6d25ccdb8781a71560081c86d which test the result of the parse. This parser i snot linked to IJ and could be used in LSP4E too.

In IJ I have implemented Snippet handler (aka SAX handler) to build an IJ Template instance to manage with advanced mean placeholder, see demo at https://github.com/redhat-developer/intellij-quarkus/pull/1006#issuecomment-1631844228
