### ISSUE TITLE
@RestClient is not suggested if I undo a first insertion. If waiting it appears again.

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-quarkus#799]
follows up on #781 

**Steps:**
1. EXEC: have `git@github.com:adietish/code-with-quarkus.git` cloned and imported into IJ
2. EXEC: open `ExtenstionsResource.java` in an editor
3. EXEC: put cursor into `extensionsService` and activate the suggestions (press Alt + Return)
```java
    @Inject
    ExtensionsService extensionsService;
```
4. ASSERT: "Insert @RestClient" is suggested
<img width="538" alt="image" src="https://user-images.githubusercontent.com/25126/228841622-d9cd51af-ea7b-4a56-bd70-329bd7ed82ce.png">

5. EXEC: select it
6. ASSERT: `@RestClient` is inserted above `@Inject`
7. EXEC: Undo
8. EXEC: activate the suggestions again an try to find "Insert @RestClient"

</br>

**Result:**
"Insert @RestClient" is not present in the suggestions. If you wait for maybe 20s it will be present again.
<img width="499" alt="image" src="https://user-images.githubusercontent.com/25126/231783058-3f57b9ad-6eef-4bbf-9a36-4fa7cc0af0b3.png">

**Comment by angelozerr** [comment]
Not really :)

**Comment by evie-lau** [comment]
This may possibly be related to the diagnostic sync issue #692

If you make a document change (adding or deleting a harmless whitespace), does it update instantly?

**Comment by angelozerr** [comment]
@evie-lau @adietish I'm rewriting diagnotic and quick fix in draft PR https://github.com/redhat-developer/intellij-quarkus/pull/792

For the moment, you need to click on the error (carret change) to compute the quick fixes.

But it should fix this issue (if you click where there is the error).

@evie-lau I noticed that you maintain a copy/paste of our repository:

 * https://github.com/OpenLiberty/liberty-tools-intellij/tree/main/src/main/java/io/openliberty/tools/intellij/lsp4mp
 * https://github.com/OpenLiberty/liberty-tools-intellij/tree/main/src/main/java/io/openliberty/tools/intellij/lsp4mp4ij/psi

IMHO I think we should have several plugins:

 * an LSP plugin (like vscode)
 * a MicroProfile plugin, that IBM could be based on (like vscode-microprofile)
 * a Quarkus plugin  (like vscode-quarkus)

@jeffmaury what do you think about this idea?

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/intellij-quarkus/pull/809
