### ISSUE TITLE
Remove duplicate twitter field in description of the plugin on Marketplace

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/intellij-quarkus#825]
<img width="979" alt="Screenshot 2023-04-27 at 10 16 40 PM" src="https://user-images.githubusercontent.com/3133356/234932858-553c5a88-9772-4f2d-9fed-19183f07704a.png">

**Comment by mohitsuman** [comment]
Also remove the Description tab for now as it redirects to repo and it is covered by Source Code label.

**Comment by sbouchet** [comment]
![Capture d’écran de 2023-04-28 10-15-09](https://user-images.githubusercontent.com/600414/235093942-951f033d-b8de-4d5b-90d4-d326b0b25c90.png)

fixed !

**Comment by fbricon** [comment]
Thanks @sbouchet!

**Comment by angelozerr** [comment]
Thanks @sbouchet !
