### ISSUE TITLE
Fix integration Tests

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#831]
As of today, last success of the integration tests jobs is 7 months old: https://github.com/redhat-developer/intellij-quarkus/actions/workflows/itests.yml?page=4&query=branch%3Amain+

Today, the integration tests don't even compile.

Either fix it or can it.

**Comment by fbricon** [comment]
since integration tests were disabled, we now have to fix them

**Comment by olkornii** [comment]
Update:
linux and windows GAs are green. Mac OS will be disabled for now. Requires code refactoring and small fixes.
Added few parameters for Process Builder: https://github.com/redhat-developer/intellij-common-ui-test-library/pull/239

**Comment by angelozerr** [comment]
That's great! Thanks @olkornii !
