### ISSUE TITLE
Improve start/stop of language servers

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/intellij-quarkus#835]
related to #838

The start/stop of language servers should be improved to avoid some freezing and some weird behavior like https://github.com/redhat-developer/intellij-quarkus/issues/752

In otherwise I would like to fix:

 * https://github.com/redhat-developer/intellij-quarkus/issues/720
 * https://github.com/redhat-developer/intellij-quarkus/issues/752
 * https://github.com/redhat-developer/intellij-quarkus/issues/748

**I noticed that there are a lot of freeze and exceptions when I open a project, I close it, I reopen it and open another project, close them, etc quickly.**

**Comment by ia3andy** [comment]
I had this problem on one of my projects where it also froze, I had to disable the plugin to make it work again. The project uses some advanced qute stuff which might not be yet handled by the plugin, but it should never freeze like this. This is really bad and should be taken seriously!

**Comment by fbricon** [comment]
@ia3andy we're taking those freezes very seriously. Expect the quality and performance of the intellij-quarkus plugin to improve dramatically in the coming weeks.

**Comment by ia3andy** [comment]
> @ia3andy we're taking those freezes very seriously. Expect the quality and performance of the intellij-quarkus plugin to improve dramatically in the coming weeks.

Ah that is a very good news, I am eager to give this a try :)

**Comment by angelozerr** [comment]
> Ah that is a very good news, I am eager to give this a try :)

Thanks for your patience!

Just one question, the freeze appears when:

 * you are editing a qute template?
 * you are closing editor?
 * you are closing a project?
 * you are closing IJ?

**Comment by ia3andy** [comment]
> > Ah that is a very good news, I am eager to give this a try :)
> 
> Thanks for your patience!
> 
> Just one question, the freeze appears when:
> 
> * you are editing a qute template?
> * you are closing editor?
> * you are closing a project?
> * you are closing IJ?

When I am opening a project containing qute templates, those qute templates are a bit exotic (fragment...)

**Comment by ia3andy** [comment]
I've managed to open it someway and I've got a lot of this: 
<img width="383" alt="image" src="https://github.com/redhat-developer/intellij-quarkus/assets/2223984/6db2d4f5-c055-4d53-96f1-7f6d17807879">
in the projects it seems

**Comment by angelozerr** [comment]
> 've managed to open it someway and I've got a lot of this:

You are using Quarkus support from Jetbreains. This error desn't comes from intellij-quarkus.

So please tell me when  freeze occurs.

**Comment by ia3andy** [comment]
> > 've managed to open it someway and I've got a lot of this:
> 
> You are using Quarkus support from Jetbreains. This error desn't comes from intellij-quarkus.
> 
> So please tell me when freeze occurs.

I am using both at the same time, let me disable the intellij one

**Comment by ia3andy** [comment]
> > > 've managed to open it someway and I've got a lot of this:
> > 
> > 
> > You are using Quarkus support from Jetbreains. This error desn't comes from intellij-quarkus.
> > So please tell me when freeze occurs.
> 
> I am using both at the same time, let me disable the intellij one

<img width="729" alt="image" src="https://github.com/redhat-developer/intellij-quarkus/assets/2223984/9d7ef083-27c7-487c-b065-21fb4bf7e587">

new freeze

**Comment by fbricon** [comment]
can you please take and share a thread dump whenever you see a freeze happening?
