### ISSUE TITLE
Mouse hover UI bug in New Quarkus Project wizard on page where you select extensions

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#85]
Navigate to: New Project > Quarkus tab -> next -> next
In some extensions categories (such as "Messaging", "Compatibility" etc. - left column) are extension (right column items), that have too long names to display in the column. When you hover with your mouse over them and then you move out of them, the text disappear. See the screenhots:

BEFORE HOVER:
<img width="1376" alt="before_hover" src="https://user-images.githubusercontent.com/43820055/81191864-cc728380-8fb9-11ea-926b-ff5887bed1dc.png">

AFTER HOVER OF THE 4 ITEMS:
<img width="1376" alt="after-hover" src="https://user-images.githubusercontent.com/43820055/81191852-c9779300-8fb9-11ea-9b9d-77527a32ad2a.png">

**Comment by zcervink** [comment]
@jeffmaury I have an update on this issue - some changes to the wizard has caused that the long items are now visible after hover. On the other hand on long items the hover causes to show the item name out of the window:

<img width="1529" alt="Snímek obrazovky 2020-06-13 v 15 41 40" src="https://user-images.githubusercontent.com/43820055/84570260-9d0b1f80-ad8c-11ea-94ec-b1d8d5c45e84.png">

**Comment by fbricon** [comment]
Closing as the hover going over the window boundaries seems done on purpose by the IntelliJ platform:

<img width="800" alt="Screenshot 2023-06-26 at 12 12 36" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/ac16a320-2499-48b3-8b76-6332cece1b93">
