### ISSUE TITLE
Check if project is a MicroProfile, Qute, etc project to map file with a language server

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/intellij-quarkus#850]
Today a language server (Qute, Quarkus, etc) is started for any Java file, any properties file even if the project is not a Quarkus, Qute project.

We should improve the server extension point to add client custom filter to check if the project is a Quarkus, Qute project to know if the file must be connected to a language server.

It will fix seveal issues:

 * if project is not a Quarkus, Qute, etc project, the opened file will not connected to a language server (and it will avoid starting MicroProfile, Qute LS for any java files, any HTML files, any properties file)
 * for Telemetry, we will send an event only if project is a Qute / MicroProfile project, because today once you open a java file even i fit is not a Quarkus, Qute project, it send an event which says that project is a Qute, Quarku sproject.

It will fix for instance this kind of comment https://github.com/redhat-developer/intellij-quarkus/issues/735#issuecomment-1541545999

`also when the currently open project is not even a Quarkus application.`

**Comment by rgrunber** [comment]
See https://github.com/redhat-developer/vscode-microprofile/blob/master/src/extension.ts#L39-L41 & https://github.com/redhat-developer/vscode-quarkus/blob/master/src/extension.ts#L47-L56 for some ideas on how to activate the MicroProfile / Qute language servers.

**Comment by angelozerr** [comment]
Thanks @rgrunber for your feedback but I think it is not enough because the idea is to associate a language file type like java file to à language server according some condition like quarkus jar in the classpath

The vscode quarkus takes care of start of language server but doesnt take of association with language server.

For instance if you have 2 projects in your workspace the first is a quarkus project, the second is à simple java project. If you open à java file from the first project it will start the quarkus l1nguage server and assiociate the java file to the java file.

If you open à java file from the second project it willb associate the file to the quarkus language serve although the jav1 file doesnt belong to a quarkus project
