### ISSUE TITLE
quarkus.kubernetes.* properties not shown or validated

### ISSUE THREAD

**Issue by anton-seredkin-de** [redhat-developer/intellij-quarkus#858]
However `quarkus.kubernetes-client.*` properties are shown in the autocomplete

**Comment by angelozerr** [comment]
Im not sure if it is the reason but if I remember thiose properies comes from some deployment dependencies which define another deployment dependencies.

In JDT we support this usecase I dont know if it is working in IJ. I will test with vscode-quarkus

**Comment by angelozerr** [comment]
@anton-seredkin-de could you share your project please.

**Comment by angelozerr** [comment]
Ok I tested with vscode-quarkus and it works great. I think it is a problem with deployment JAR (which is not a simple topic), I will investigate the problem when I will have time.

**Comment by angelozerr** [comment]
@anton-seredkin-de I'm fixing this issue, see demo at https://github.com/redhat-developer/intellij-quarkus/pull/1040#issuecomment-1648149130

**Comment by fbricon** [comment]
Let's close this one now, as it works as expected, and we'll deal with the performance improvements in a later PR.
