### ISSUE TITLE
New Quarkus project can be created without the RESTEasy JAX-RS extension checked in the wizard

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#88]
The RESTEasy JAX-RS extension is included by default. The wizard should have checked to include this extension by default and the checkbox should be disabled (user cannot uncheck it).

<img width="1376" alt="Snímek obrazovky 2020-05-09 v 22" src="https://user-images.githubusercontent.com/43820055/81484452-d4deee80-9245-11ea-9313-60bc037d6821.png">

**Comment by jeffmaury** [comment]
Duplicates of #42
