### ISSUE TITLE
Respect language server settings to show language server process in console

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/intellij-quarkus#880]
If language servers are "off" trace, sometimes when the language server stopped, the language server process tree node appears:

![image](https://github.com/redhat-developer/intellij-quarkus/assets/1932211/e29f34f4-766d-4136-96f7-196792d05dc2)

although settings trace is "off".

**Comment by fbricon** [comment]
We still need to know the status of the server, that's orthogonal to the trace status

**Comment by angelozerr** [comment]
Sorry @fbricon I dont understand what you mean. What do you want I do?
