### ISSUE TITLE
New Java Project contains 2 Quarkus items to create new project

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#89]
- I think there should be only 1 item, because one of that item completely covers the other
- See the printscreens:

<img width="1376" alt="Snímek obrazovky 2020-05-11 v 10 15 02" src="https://user-images.githubusercontent.com/43820055/81540402-e9200a00-9371-11ea-8afa-df1a908cf906.png">
<img width="1376" alt="Snímek obrazovky 2020-05-11 v 10 15 05" src="https://user-images.githubusercontent.com/43820055/81540393-e4f3ec80-9371-11ea-99af-b4a24b1c8aac.png">

**Comment by fbricon** [comment]
IMO those wizards are useless, they're lacking all proper dependencies, they should be removed. 
@jeffmaury wdyt?

**Comment by jeffmaury** [comment]
Yes for the one that just add the Quarkus library

**Comment by jeffmaury** [comment]
I would say only one is coming from us.
