### ISSUE TITLE
Cannot start IntelliJ using the ./gradlew runIde cmd on Java 11

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/intellij-quarkus#90]
When I run the **./gradlew runIde** cmd, exception will pop up during starting the IDE:

<img width="976" alt="Snímek obrazovky 2020-05-11 v 12" src="https://user-images.githubusercontent.com/43820055/81669273-4a191200-9446-11ea-985a-fcb1cefe833f.png">

**Comment by jeffmaury** [comment]
Seems Gradle is using a Java8 runtime to run IJ but using your JAVA_HOME to compile
