### ISSUE TITLE
Wrong "include" codelens ranges in Qute pages

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#912]
Codelens should align with matching the opening `{`
<img width="353" alt="Screenshot 2023-06-01 at 17 50 24" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/4372b112-aa37-4724-9896-9d58069fbd15">

**Comment by fbricon** [comment]
am I the only one triggered by this? @ia3andy @FroMage @mkouba?

**Comment by angelozerr** [comment]
This position is computed by the Qute LS. In vscode it ignore the character position.

Qute ls report the position of the parameter and not of the section.

If you think it is really better to set the position aligned with #insert please create an issue at quarkus-ls but please note If template will look like this

Bla bla {#insert title

The codelens will be aligned with insertion and not with Bla

**Comment by FroMage** [comment]
I've no idea what @fbricon described :)

**Comment by fbricon** [comment]
@FroMage The alignment of the code lenses above the insert sections

**Comment by FroMage** [comment]
So, you guys really set the bar super high for me. I _think_ that a codelens is the "X references" gray text thingy, right?

If yes, then I understand the issue.

Semantically, the reference refers to the variable, so the current display is correct. Visually, it would look nicer if it were aligned with `insert` like @fbricon says. So… do what you want, they're both correct :)

**Comment by fbricon** [comment]
not important enough, closing
