### ISSUE TITLE
Qute signature resolution of method parameters must ignore annotations

### ISSUE THREAD

**Issue by ia3andy** [redhat-developer/intellij-quarkus#935]
project is https://github.com/ia3andy/quarkus-blast
plugin version is 1.20.0

<img width="1141" alt="image" src="https://github.com/redhat-developer/quarkus-ls/assets/2223984/61722918-ddd9-4793-bea5-2e4f06f5affe">

In this case it's not an error, the last parameter is a `@RestForm` so not part of the uri.

@fromage do you have some doc about this? It's true that it's a bit confusing at first.

**Comment by angelozerr** [comment]
> I'm pretty sure we already discussed this with @angelozerr and the non-path/query parameters are supposed to be ignored.

Indeed and it is working on vscode-quarkus. Let me investigate the problem with IJ.

**Comment by angelozerr** [comment]
Ok there is a bug when signature play method is built. You can see that in your screenshot. You have 

`play(Long, NotNullint,...)`

although it should be:

`play(Long, int,...)`

The signature built must ignore the annotations (like @NotNull in this case).

**Comment by fbricon** [comment]
@ia3andy you can try the build from https://github.com/redhat-developer/intellij-quarkus/actions/runs/5222208173
