### ISSUE TITLE
Codelens don't align when indentation is `tab`

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#947]
Given this code, idented with tabs :

```java
package org.acme;

import io.quarkus.qute.Template;
import io.quarkus.qute.TemplateInstance;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.core.MediaType;

import static java.util.Objects.requireNonNull;

@Path("/path")
public class Foo {

	private final Template page;

	public Foo(Template page) {
		this.page = requireNonNull(page, "page is required");
	}

	@GET
	@Produces(MediaType.TEXT_HTML)
	public TemplateInstance get(@QueryParam("name") String name) {
		return page.data("name", name);
	}

}
```

template and path codelens don't align:
<img width="593" alt="Screenshot 2023-06-13 at 11 56 21" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/84b7cdb4-28a6-49dd-b719-47d91bb72096">

**Comment by fbricon** [comment]
Looks like we can replace

https://github.com/redhat-developer/intellij-quarkus/blob/6ec29f8968be2f3b16a0e91ce0ace14fda2f986d/src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/codelens/LSPCodelensInlayProvider.java#L114-L115

with something super ugly like 

```java
        int[] col = new int[1];
        UIUtil.invokeAndWaitIfNeeded((Runnable) () -> {
                col[0] = editor.offsetToVisualPosition(offset).getColumn(); // can only run in the EDT
        });
        int column = col[0];
```

This works :
<img width="872" alt="Screenshot 2023-06-28 at 14 20 34" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/45b3c4ad-e7f7-409c-929d-7a26ae3aa172">

Can anyone think of a more elegant solution?

**Comment by angelozerr** [comment]
I fear that using `invokeAndWaitIfNeeded `for each codelens could degrade the performance.

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/intellij-quarkus/issues/947
