### ISSUE TITLE
Clicking Next button is slow in Quarkus wizard

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#973]
Following changes on the Quarkus wizard in #969, @angelozerr mentioned: 

> I have noticed that click on Next button is slow. I think it is because it collect Quarkus extension, but I think we should manage a progress monitor or something like this which explains that Quarkus extensions are collected. At first I though it didn't work and click on Next button several times.

2 remote calls are performed on the UI thread :
- QuarkusModuleInfoStep loads the Quarkus versions
- QuarkusExtensionsStep loads the Quarkus extensions

**Comment by angelozerr** [comment]
I tested the Quarkus wizard from Ultimate which looks like our wizard and the UI wizard pages are displayed immediatly.

**Comment by fbricon** [comment]
Fixing this should also cover #273
