### ISSUE TITLE
Auto-completion of Qute tags

### ISSUE THREAD

**Issue by ia3andy** [redhat-developer/intellij-quarkus#975]
when using auto-completion of `{#if` for example, the closing tag is added with wrong indent:
<img width="407" alt="image" src="https://github.com/redhat-developer/quarkus-ls/assets/2223984/919771d7-4a9b-477f-b31f-0dc015c12c5a">

I think it would be better to keep the snippet on one line and let the user decide of the rest.

**Comment by angelozerr** [comment]
I move this issue to IJ Quarkus since it is a bug in IJ Quarkus. Completion has so many bugs and I'm working on it.

The issue that you report is that;

 * IJ LSP cannot support LSP `InsertTextMode.AdjustIndentation`
 * IJ LSP cannot support snippet syntax.

**Comment by angelozerr** [comment]
@ia3andy before working on your issue I need to work on https://github.com/redhat-developer/intellij-quarkus/issues/787

**Comment by ia3andy** [comment]
@angelozerr no worries :) just reporting!

**Comment by fbricon** [comment]
@ia3andy you can try the CI build from https://github.com/redhat-developer/intellij-quarkus/actions/runs/5376642773?pr=954, and overall keep an eye on #954

**Comment by angelozerr** [comment]
> @ia3andy you can try the CI build from https://github.com/redhat-developer/intellij-quarkus/actions/runs/5376642773?pr=954, and overall keep an eye on https://github.com/redhat-developer/intellij-quarkus/pull/954

This build shouldfix indentation problem but not cursor position. Cursor position will be fixed when I will implement snippet support with completion.

**Comment by angelozerr** [comment]
> @angelozerr no worries :) just reporting!

Yes sure! I'm happy to work on issues expected by users:)
