### ISSUE TITLE
Auto-indentation (and reformat) is not working on qute html files

### ISSUE THREAD

**Issue by ia3andy** [redhat-developer/intellij-quarkus#992]
@angelozerr This is the most annoying issue at the moment I believe.

To reproduce use https://github.com/ia3andy/quarkus-blast

While coding:
- Open any template
- Add a `<div>`, it will close it
- type enter in the middle, the other is put on the start of the other line

Formating:
- Break the formatting (indentation) of a qute template
- Use Code>Reformat Code
- Nothing changes

Fixing this might fix #975

**Comment by fbricon** [comment]
@ia3andy please try the CI build from https://github.com/redhat-developer/intellij-quarkus/actions/runs/5507675944

**Comment by ia3andy** [comment]
Good!

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/intellij-quarkus/pull/954

**Comment by ia3andy** [comment]
@fbricon we discussed it with @angelozerr, the auto-indentation is working which is already a big step forward but it still misses an important part which is the auto indentation of the qute sections (if, ...).

I guess we can close this issue and open a new one.

**Comment by angelozerr** [comment]
Indded please create a new issue with auto indent for qute
