### ISSUE TITLE
CSS completion doesn't work in Qute HTML templates

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/intellij-quarkus#998]
In https://github.com/ia3andy/quarkus-blast/blob/main/src/main/resources/templates/layout/sidebar.html

Class autocompletion is available in some places:
<img width="846" alt="image (3)" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/0af7868c-5037-4de3-966c-b94322bc8b3b">

not in others:
<img width="419" alt="image (4)" src="https://github.com/redhat-developer/intellij-quarkus/assets/148698/7549652b-fc4c-44f6-807d-04d67b0e0623">

Mentioned by @ia3andy

**Comment by fbricon** [comment]
@angelozerr with #954, I don't even get the 1st css completion

**Comment by fbricon** [comment]
So it turns out the CSS completion is provided in IDEA Ultimate, not Community.
I tested the CI build from https://github.com/redhat-developer/intellij-quarkus/actions/runs/5507675944, on IDEA Ultimate EAP. After overriding the file type with `Qute (from 'Quarkus Tools' plugin)`

![Screenshot 2023-07-10 at 14 13 00](https://github.com/redhat-developer/intellij-quarkus/assets/148698/4437ab34-2111-4c5d-bcd7-dd96341a1ea3)

and CSS completion still worked everywhere, apparently.

**Comment by angelozerr** [comment]
I think we can close this issue, no?
